### ISSUE TITLE
`travis encrypt` too short

### ISSUE THREAD

**Issue by rbpasker** [travis-ci/travis.rb#100]
I have a 194 character environment variable, but when I try to do a travis encrypt, i get `data too large for key size`

i'm not sure why there is a size restriction, or how big it is (do i need to do a binary search?), but the fact is that its just too small

compare heroku which allows 16kb for environment variable space, and they have no problem with 194 characters.

https://devcenter.heroku.com/articles/config-vars#limits

**Comment by jaraco** [comment]
It seems some projects have 128 byte keys and others 512 byte keys. Is there any way to tell which keys are available for which projects? Is it possible to refresh a project with the larger key?
