### ISSUE TITLE
whitespace stripped on `travis encrypt foo=bar --add`

### ISSUE THREAD

**Issue by till** [travis-ci/travis.rb#144]
So when I do this, the whitespace (indenting, etc.) is stripped.

**Comment by jeffrey-aguilera** [comment]
Wont fix? Really?  If the off-the-shelf parsers don't work, then write your own.  Or warn before destroying the file. Or just remove the feature.  You should not reformat and discard comments as a side-effect of this command.  Principle of least surprise.

**Comment by jakubholynet** [comment]
Or just print the line to be added to .travis.yml to stdout and let people add it manually. After all the command is `encrypt` not `encrypt and add to file`.

**Comment by sarahhodne** [comment]
> Or just print the line to be added to .travis.yml to stdout and let people add it manually. After all the command is encrypt not encrypt and add to file.

This is what the command does by default, it only modifies the .travis.yml if you pass `--add`.
