### ISSUE TITLE
Pry dependency?

### ISSUE THREAD

**Issue by amacneil** [travis-ci/travis.rb#245]
Why does Travis gem depend on pry?!

Worse, why does it depend on outdated version?!

Now, Travis annoys me endlessly about "Outdated CLI version", and I can't update because it depend on an old version of Pry.

Plz fix - either remove the outdated pry dependency, or remove the annoying outdated CLI warning :)

**Comment by coderanger** [comment]
Bumping this for great justice. Been a long while and it would be nice to update the 0.10 lockout.

**Comment by cardil** [comment]
+1

**Comment by deivid-rodriguez** [comment]
Any plans to update this dependency guys? Thanks!

**Comment by spovich** [comment]
+1, please get this fixed!

**Comment by simi** [comment]
What about to vendorize namespaced pry for now? I can try to open PR if it is welcomed.

**Comment by bbirch** [comment]
+1

**Comment by a2z9** [comment]
o k.

**Comment by a2z9** [comment]
what must i do now ?

**Comment by BanzaiMan** [comment]
I don't think `pry` is a requirement at this point. I'm closing this now.
