### ISSUE TITLE
Problems retrieving logs body using the API

### ISSUE THREAD

**Issue by mottalrd** [travis-ci/travis.rb#249]
Hello,

I am trying to download job logs using the API but till now I didn't succeed.
Here I am querying a Pro account using the Ruby gem.

```
[1] $ job
=> #<Travis::Client::Job: HouseTrip/HouseTrip-Web-App#9000.1>
[2] $ job.log
=> #<Travis::Client::Artifact: 9916087>
[3] $ job.log.body
Travis::Client::Error: SSL error: could not verify peer
from /Users/motta/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/travis-1.6.17/lib/travis/client/session.rb:212:in `raw'
```

If I try using a plain HTTP client I have the same issue. 
Here I am using [Postman](https://chrome.google.com/webstore/detail/postman-rest-client/fdmmgilgnpjigdojojpjoooidkmcomcm?hl=en) and that's what I see.

I can get the Job

![postman2](https://cloud.githubusercontent.com/assets/1802500/5226734/38e41798-76ea-11e4-92a9-4860982a2777.png)

But I can't get the body, specifically I get a blank body.

![postman](https://cloud.githubusercontent.com/assets/1802500/5226738/468f52cc-76ea-11e4-925b-2189fa68390f.png)

Let me know if I can provide more info.
Thank you

**Comment by rkh** [comment]
I can reproduce the issue.
