### ISSUE TITLE
Travis CLI doesn't handle url.<base>.insteadOf

### ISSUE THREAD

**Issue by hoelzro** [travis-ci/travis.rb#258]
Hi there,

To make my Git life a little easier, I make use of the `insteadOf` configuration variable in my `gitconfig`.  I have the following in my `~/.gitconfig`:

    [url "git@github.com:Threadless/"]
        insteadOf = work:

...so that I can type `git clone work:project` instead of `git clone git@github.com:Threadless/project`.  However, when I do this, the travis CLI isn't able to pick up the repo's name:

    $ git clone work:project
    ...
    $ cd project/
    $ travis cache
    Can't figure out GitHub repo name. Ensure you're in the repo directory, or specify the repo name via the -r option (e.g. travis <command> -r <repo-name>)

I've gotten around this in my own scripting by grabbing output from `git remote show -n origin`, and I was hoping that the Travis CLI could do something similar.  If you fine folks approve of this approach, I can implement it and submit a PR.

Thanks!

**Comment by rkh** [comment]
PR would be welcome. As a workaround, you can specify the slug via -R once.

Konstantin

**Comment by hoelzro** [comment]
@rkh Thanks; PR is ready at #259
