### ISSUE TITLE
Gem install: travis executable in /usr/bin (OS X Yosemite)

### ISSUE THREAD

**Issue by 0culus** [travis-ci/travis.rb#270]
Hi,

I installed the gem according to the directions, and it put the travis executable in `/usr/bin`. This means that I need sudo to run it and I can't seem to get either bash or fish to find it in the path. This doesn't seem right at all. Any ideas? 

Thanks!

**Comment by BanzaiMan** [comment]
How exactly did you install it? What does `ls -l /usr/bin/travis` show?

**Comment by 0culus** [comment]
I installed it exactly as shown in the readme. 

I get: `-rwx------  1 root  wheel  508 Feb  2 11:17 /usr/bin/travis`

**Comment by BanzaiMan** [comment]
I don't see a mention of `sudo` in OS X installation instructions. https://github.com/travis-ci/travis.rb#installation

You might be able to fix this by setting the file world-executable (`sudo chmod 755 /usr/bin/travis`), but there may be other obstacles.

**Comment by 0culus** [comment]
chmod actually seems to have fixed it, thanks.
