### ISSUE TITLE
How do I install it without root?

### ISSUE THREAD

**Issue by chrisbra** [travis-ci/travis.rb#273]
As per the title. I started with the installation instructions:

```
0 3483 chrisbra@debian ~/code/git/travis.rb (git)-[master]- % gem install travis -v 1.7.5 --no-rdoc --no-ri
Fetching: multipart-post-2.0.0.gem (100%)
ERROR:  While executing gem ... (Errno::EACCES)
Permission denied @ dir_s_mkdir - /var/lib/gems
```

I do not want to install it systemwide, so how can I tell it to install below $HOME?

**Comment by rkh** [comment]
You should add a writable path to the $GEM_PATH variable and set $GEM_HOME
to that value. Note that you will also make sure it's bin directory is on
the $PATH.

We are planning to ship a CLI version by other means than rubygems, to
(amongst other things) make it easier for non-ruby developers to get it
running.

**Comment by chrisbra** [comment]
Am 2015-02-19 10:09, schrieb Konstantin Haase:
> You should add a writable path to the $GEM_PATH variable and set
> $GEM_HOME
>  to that value. Note that you will also make sure it's bin directory
> is on
>  the $PATH.
> 
>  We are planning to ship a CLI version by other means than rubygems,
> to
>  (amongst other things) make it easier for non-ruby developers to get
> it
>  running.


You are right, I am not a ruby developer. So please document that on
the frontpage (where I copied the install instructions for ubuntu).

BTW: I only need that to invalidate the cache, but I would rather have
a button on the webpage to discard the old cache...

Thanks,

Christian

**Comment by muhuk** [comment]
Please make the client something non-rubyists can also use!

        $ GEM_HOME=/home/muhuk/.gem GEM_PATH=/home/muhuk/.gem gem install travis


        Fetching: multipart-post-2.0.0.gem (100%)
        Successfully installed multipart-post-2.0.0
        Fetching: faraday-0.9.2.gem (100%)
        Successfully installed faraday-0.9.2
        Fetching: faraday_middleware-0.10.0.gem (100%)
        Successfully installed faraday_middleware-0.10.0
        Fetching: highline-1.7.8.gem (100%)
        Successfully installed highline-1.7.8
        Fetching: backports-3.6.6.gem (100%)
        Successfully installed backports-3.6.6
        Fetching: net-http-pipeline-1.0.1.gem (100%)
        Successfully installed net-http-pipeline-1.0.1
        Fetching: net-http-persistent-2.9.4.gem (100%)
        Successfully installed net-http-persistent-2.9.4
        Fetching: addressable-2.3.8.gem (100%)
        Successfully installed addressable-2.3.8
        Fetching: multi_json-1.11.2.gem (100%)
        Successfully installed multi_json-1.11.2
        Fetching: gh-0.14.0.gem (100%)
        Successfully installed gh-0.14.0
        Fetching: launchy-2.4.3.gem (100%)
        Successfully installed launchy-2.4.3
        Fetching: coderay-1.1.0.gem (100%)
        Successfully installed coderay-1.1.0
        Fetching: slop-3.6.0.gem (100%)
        Successfully installed slop-3.6.0
        Fetching: method_source-0.8.2.gem (100%)
        Successfully installed method_source-0.8.2
        Fetching: pry-0.10.0.rc1.gem (100%)
        Successfully installed pry-0.10.0.rc1
        Fetching: ffi-1.9.10.gem (100%)
        Building native extensions.  This could take a while...
        ERROR:  Error installing travis:
                ERROR: Failed to build gem native extension.

            /usr/bin/ruby2.1 extconf.rb
        mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

        extconf failed, exit code 1

**Comment by gingerik** [comment]
@muhuk - I think you need to run `apt-get install ruby-dev` as root first.

**Comment by muhuk** [comment]
@gingerik sorry for the delayed response.

I can confirm I have `ruby-dev`. (Probably I have it installed before trying to install the client.)

I was trying to get a token. Solved the issue some other way (`travis` is still not installed on my machine), but I can't remember how. I think I have used the token in my account page.

Thanks for the info though. It is very well documented too.

**Comment by BanzaiMan** [comment]
Closing in favor of #758. It no longer depends on native extensions, so the installation should be easier. If the issue persists, feel free to open a new one.
