### ISSUE TITLE
docs suggest reusing key and IV which breaks security

### ISSUE THREAD

**Issue by johnduffell** [travis-ci/travis.rb#274]
On http://docs.travis-ci.com/user/encrypting-files/ it says
.....
Workaround 1 #

Reuse the key and iv values.
.....
However you should never ever reuse an IV if you want to use the same key - for an example see http://en.wikipedia.org/wiki/Initialization_vector "In stream cipher encryption uniqueness is crucially important as plaintext may be trivially recovered otherwise."

**Comment by BanzaiMan** [comment]
Thanks for pointing this out. I think removing the first option will be the best option going forward.

**Comment by johnduffell** [comment]
:+1: looks good
TBH the simplest secure way is to encrypt them all separately and use the -pass parameter to openssl with the same password.  This is secure as it'll generate a key from the password and a random IV. It will store the IV in the file, but the key will remain secret.  Encrypting the same file repeatedly will (correctly) produce a different output every time, if it didn't it wouldn't be secure.
