### ISSUE TITLE
Possible to change faraday adapter?

### ISSUE THREAD

**Issue by waynehoover** [travis-ci/travis.rb#277]
It looks like the faraday adapter can not be changed:

https://github.com/travis-ci/travis.rb/blob/master/lib/travis/client/session.rb#L31

If I wanted to pass in another adapter, say `:excon` how could I do that with a global session?

**Comment by BanzaiMan** [comment]
At the moment (5 years later), this is still not possible. If there is a strong demand for this feature, we can look into implementing it, but Typhoeus (if available) and Net::HTTP should be sufficient for now.
