### ISSUE TITLE
How to create a pro client instance?

### ISSUE THREAD

**Issue by waynehoover** [travis-ci/travis.rb#280]
Doing this `Travis::Pro::Client.new` gives this `NameError: uninitialized constant Travis::Pro::Client`

**Comment by waynehoover** [comment]
Never mind, to get what I was after this is how I did it `Travis::Pro.session.config`

**Comment by rkh** [comment]
For the record, this is how you'd do it:

``` ruby
client = Travis::Client.new('https://api.travis-ci.com/')
client.config
```
