### ISSUE TITLE
travis-1.7.6: `Outdated CLI version`

### ISSUE THREAD

**Issue by fniephaus** [travis-ci/travis.rb#288]
Hi @rkh,

It looks like there's an issue with the travis command line client. I've installed the latest version, but it wouldn't let me encrypt anything. With ```--skip-version-check``` I was able to do it, but I guess it's supposed to work without that if the cli tool is up-to-date and `travis version` tells me it is. I'm sure you already know how to fix this.

Regards,
Fabio

```bash
fniephaus:my-repo (master*) $ gem install travis
Successfully installed travis-1.7.6
Parsing documentation for travis-1.7.6
Done installing documentation for travis after 1 seconds
1 gem installed
fniephaus:my-repo (master*) $ travis encrypt "bla:blup" --add notifications.slack
Outdated CLI version, run `gem install travis` or use --skip-version-check.
[1]    3741 exit 1     travis encrypt "bla:blup" --add notifications.slack
```

**Comment by rkh** [comment]
Hm. That's strange. With 1.7.6, it shouldn't even do the `exit 1` anymore on an outdated version. What does `travis report --skip-version-check` give you?

**Comment by fniephaus** [comment]
It *is* strange, everything looks fine but even a reinstall doesn't help. Here you go:

```
System
Ruby:                     Ruby 2.2.1-p85
Operating System:         Mac OS X 10.10.3
RubyGems:                 RubyGems 2.4.6

CLI
Version:                  1.7.6
Plugins:                  none
Auto-Completion:          no
Last Version Check:       never
```

**Comment by rkh** [comment]
Can you check if you have a `~/.travis/config.yml` and whether it contains a `last_check` section (feel free to publish anything from that file except for the `endpoints` section if you have one)?

**Comment by fniephaus** [comment]
```yml
checked_completion: true
completion_version: 1.7.6
last_check: {}
endpoints: ...
```

**Comment by fniephaus** [comment]
Problem seems to be gone since `v1.7.7`...

**Comment by rkh** [comment]
Nice.

**Comment by georgettica** [comment]
I get the same error on the `Outdated CLI version.`

@rkh  Should this issue be reopened?
