### ISSUE TITLE
How can I encrypt files that are in different dir?

### ISSUE THREAD

**Issue by tomoima525** [travis-ci/travis.rb#290]
Hi,
I have an Android project repository that I want to start Travis CI.
There are some files that are secret and ignored from the repo. They are in different directories.
**File1:**
(project_root)/app/private.properties
**File2:**
(project_root)/keys/debugkey.gradle
**File3:**
(project_root)/keys/debug.keystore

I read the doc [here](http://docs.travis-ci.com/user/encrypting-files/) and know that if files are in the same dir you can create a tar and encrypt them. But what should I do when each files are in different directories?
Any support is appreciated. Thank you.

**Comment by BanzaiMan** [comment]
You can create an archive with these three files, encrypt it, and expand as you wish.

```sh-session
cd (project_root)
tar cvzf secrets.tar.gz app/private.properties keys/debugkey.gradle keys/debug.keystore
travis encrypt-file secrets.tar.gz
⋮
```

**Comment by tomoima525** [comment]
@BanzaiMan Thanks, it worked!

**Comment by BanzaiMan** [comment]
Great to hear!
