### ISSUE TITLE
travis encrypt throws "no such file or directory" error

### ISSUE THREAD

**Issue by maketestingharder** [travis-ci/travis.rb#296]
running below comand
```travis encrypt GH_TOKEN=<TOKEN>```
throws below error
```No such file or directory - git config --get travis.slug
for a full error report, run travis report```

```travis report```
gave me this
>An error occurred running \`travis encrypt\`:
    Errno::ENOENT: No such file or directory - git config --get travis.slug
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/travis-1.7.6/lib/travis/cli/
repo_command.rb:87:in \`\`'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/travis-1.7.6/lib/travis/cli/
repo_command.rb:87:in \`load_slug'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/travis-1.7.6/lib/travis/cli/
repo_command.rb:59:in \`find_slug'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/travis-1.7.6/lib/travis/cli/
repo_command.rb:21:in \`setup'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/travis-1.7.6/lib/travis/cli/
command.rb:197:in \`execute'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/travis-1.7.6/lib/travis/cli.
rb:64:in \`run'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/travis-1.7.6/bin/travis:18:i
n \`<top (required)>'
        from C:/Ruby22-x64/bin/travis:23:in \`load'
        from C:/Ruby22-x64/bin/travis:23:in \`<main>'

this has happened when I was trying to find a config for deploying jekyll page to github pages
(I'm completely new to ruby, travis, jekyll so please be gentle if I did not attach something important and obvious)

**Comment by schellkenig** [comment]
Do you have git in your path? To verify just open a cmd and type in git. If they command is not found add your git bin directory to your path variable and try again.

**Comment by ader9** [comment]
I had the same problem, and this solution worked me! Thank you.

**Comment by nicolaslattuada** [comment]
You have to pass the repo as command line argument, --repo=user/your-repo

**Comment by AraHaan** [comment]
This happens even if I install travis locally on my computer so I can configure travis privately for my python package (so I can encrypt my pypi password without releasing the repo to github yet only to make my pypi password vieable to anyone). I really have no idea how to add git to path either but I use git bash for commiting things to github.

**Comment by BanzaiMan** [comment]
The original report indicates that it occurred on Windows. Do we have any report of this happening anywhere else?

**Comment by AraHaan** [comment]
Not that I know of.

**Comment by AraHaan** [comment]
ok, got it to work but only if I do ``travis encrypt deploy.password=yourpypipasswordhere -r AraHaan/datetime_diff``
