### ISSUE TITLE
CLI exit status for not passed builds shouldn't be 0

### ISSUE THREAD

**Issue by netmilk** [travis-ci/travis.rb#297]
I think that exit status for any other state for the `show` or `status` should be greater than zero. My motivation is to write a pre publish shell script for a `npm` package which will block release when master is not passing or not built yet and if the commit message of last build does not match commit message of the last local commit.

Current behavior for `status`: 
```
kolotoc:gavel.js netmilk$ travis status
echo#build #263 started
kolotoc:gavel.js netmilk$ echo $?
0
```

And for `show`:
```
kolotoc:gavel.js netmilk$ travis show
Build #263:  Bumped version
State:         started
Type:          push
Branch:        master
Compare URL:   https://github.com/apiaryio/gavel.js/compare/b0800726a5aa...edcb17a9191c
Duration:      none
Started:       2015-05-25 16:09:42
Finished:      not yet

#263.1 started:  32 sec         node_js: 0.8, os: linux
#263.2 started:  32 sec         node_js: 0.1, os: linux
#263.3 started:  24 sec         node_js: 0.12, os: linux
#263.4 started:  33 sec         node_js: iojs, os: linux
kolotoc:gavel.js netmilk$ echo $?
0
```

**Comment by rkh** [comment]
Can reproduce.

**Comment by rkh** [comment]
Hi @netmilk. The command doesn't set the status code by default. You'll have to pass the `-x` flag.

**Comment by netmilk** [comment]
Sweet  :candy: !
