### ISSUE TITLE
Installation fails on windows

### ISSUE THREAD

**Issue by basarat** [travis-ci/travis.rb#300]
Log:

```bash
D:\>gem install travis
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Not Found 404 (https://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/pry-0.9.12.6-x86-mingw32.gemspec.rz)
```

**Comment by BanzaiMan** [comment]
This is an error from rubygems.org, no? The URL returns 404 for me, too. I suggest getting help from http://help.rubygems.org/.

**Comment by basarat** [comment]
Just installed fine for me right now on another windows machine so closing it. Hopefully it works on the other machine I tried earlier (but I don't have access to that right now). Will reopen / report elsewhere (https://github.com/rubygems/rubygems/issues) if it comes up again. :rose:
