### ISSUE TITLE
Unable to add heroku deploy section after moving repo from pro to org

### ISSUE THREAD

**Issue by kevgathuku** [travis-ci/travis.rb#301]
I have a repo that I moved from pro to org.
When I was using pro, I had heroku deployment set up and it worked like a charm.
On moving it to travis org, the `travis setup heroku` ran successfully but all heroku deploys failed with this error
```
Expected(200) <=> Actual(401 Unauthorized)
body: "{\"id\":\"unauthorized\",\"error\":\"Invalid credentials provided.\"}" (wrong API key?)
failed to deploy
```
After around 24 hours, on trying to add the heroku section automatically as documented in the [Heroku deployment docs](http://docs.travis-ci.com/user/deployment/heroku/), through the 
`travis setup heroku` command, I am now getting this error:
```
not logged in, please run travis login --pro
```
Does this have something to do with the move of the repo from pro to org?
I would really appreciate any help. I've exhausted all other options. Thanks in advance.

**Comment by BanzaiMan** [comment]
Try `travis login --org` and `travis setup heroku --org`. Most likely your repo is still set up to talk to the .com API endpoint, and you need to talk to the .org endpoint instead.

**Comment by kevgathuku** [comment]
I had already run `travis login --org` previously when it was still returning an error.
Running `travis setup heroku --org` fixed it for me. The Heroku Deploys are successful now.
Thanks a lot.
