### ISSUE TITLE
travis client doesn't appear to be listening on events

### ISSUE THREAD

**Issue by imtayadeway** [travis-ci/travis.rb#304]
On using v.1.7.7, my travis client doesn't appear to be listening on events.

To reproduce, I just ran the example from the README:

```ruby
sandbox = Travis::Repository.find("miq-test/sandbox")
# => #<Travis::Repository: miq-test/sandbox>

Travis.listen(sandbox) do |stream|
  stream.on("build:started", "build:finished") do |event|
    puts "#{event.repository.slug} just #{event.build.state}"
  end
end
```

And I get nothing when starting/stopping a build. Not sure if this is related to https://github.com/travis-ci/travis.rb/issues/302, so I created a new issue. Thanks!

**Comment by jrafanie** [comment]
@imtayadeway can you try by unlocking travis to >= 1.7.6?

I got this when bundling locally with ruby 2.2.2:
```
...
Installing typhoeus 0.7.3 (was 0.7.2)
Installing backports 3.6.6 (was 3.6.5)
Installing highline 1.7.3 (was 1.7.2)
Installing travis 1.8.0 (was 1.7.7)
```

Then, when I run the CLI monitor:
```
$ bundle exec travis monitor --org --debug
** Loading "/Users/joerafaniello/.travis/config.yml"
** Using notifications: Dummy
** GET "config"
**   took 0.1 seconds
** GET "users/"
**   took 0.45 seconds
Monitoring travis-ci.org:
2015-08-18 13:39:53 ManageIQ/manageiq#12440.7 passed
2015-08-18 13:40:02 ManageIQ/manageiq#12232.4 started
2015-08-18 13:40:44 ManageIQ/manageiq#12232.3 passed
2015-08-18 13:40:56 ManageIQ/manageiq#12232.5 started
```

**Comment by rkh** [comment]
Does the `monitor` command work for you?

**Comment by imtayadeway** [comment]
@rkh `monitor` works, yes. it didn't for me previously, as in #302, however on the latest release that now works, but the snippet I pasted above does not

**Comment by BanzaiMan** [comment]
For `monitor` issue, please see #353.

I'm closing this to streamline the feedback loop.
