### ISSUE TITLE
Can't use the "travis" command line tool on Ubuntu 15.04 (installed from the official repository)

### ISSUE THREAD

**Issue by ByteCommander** [travis-ci/travis.rb#305]
As I said, I use Ubuntu 15.04 and installed `travis` from the repository using `sudo apt-get install travis`.
Now, I can't run any commands like `travis encrypt`. I always get the error `Unknown parameter: "encrypt".` or whatever command I try.

Running it without command argument, it asks for a trajectory file. What is this and how do I create one? I was not able to find anything about this anywhere. 

Thank you for responding and helping me out. I really need this encryption feature.

**Comment by Joshua-Anderson** [comment]
Travis in apt != to Travis.rb. They are two different programs with the same name. `apt-get purge travis` and then follow the [installation instructions](https://github.com/travis-ci/travis.rb#installation)

**Comment by ByteCommander** [comment]
You are right! I am sorry, I thought Ubuntu might have simplified the installation for such an important development tool by adding it to the repositories. That was not the case. But I am really surprised that I did not notice using an entirely and not at all related program... >.<
