### ISSUE TITLE
Using behind corporate proxy on linux

### ISSUE THREAD

**Issue by adriens** [travis-ci/travis.rb#308]
Hi guys,

i really like Travis and share it as much as i can. I often use the console from home, but i could not find how to run the console behind a corporate proxy : any hint on how to do that ?
Does it use any env variable, or conf file to tell Travis console how to go on the web ?

Thank you in advance for your help.

Kind Regards,

Adrien

**Comment by FloFra** [comment]
Duplicate of #262.
