### ISSUE TITLE
Console tells 'travis` is not installed

### ISSUE THREAD

**Issue by yurko** [travis-ci/travis.rb#309]
After succesfully installation with ```gem install travis```, after ```travis login``` console tells that 'travis' is not installed and can install it with ````sudo apt-get install travis````. How to run it travis from gem?

**Comment by rkh** [comment]
I'd guess this means that your RubyGems isn't set up properly. Does `ruby -S travis login` work?

**Comment by yurko** [comment]
@rkh, thanx, ````ruby -S travis login````` works

**Comment by rkh** [comment]
That means your path is probably not set up correctly then.
