### ISSUE TITLE
travis console behind corporate proxy

### ISSUE THREAD

**Issue by adriens** [travis-ci/travis.rb#312]
Hi,

can you pleas provide some guidelines on how to use travis console behind a corporate proxy ?

Thank you in advance for your help.

Best Regards,

Adrien

**Comment by rkh** [comment]
What kind of proxy? HTTP proxy?

**Comment by adriens** [comment]
Hi, yes, sorry, HTTP proxy. my http_proxy and https_proxy variables are set (linux) but it seems like they have no effect on travis console.

**Comment by rkh** [comment]
Yes, I think the CLI just ignores them atm.

**Comment by adriens** [comment]
@rkh : is there any workaround ?

**Comment by FloFra** [comment]
Duplicate of #262.
