### ISSUE TITLE
Can't use encrypt on something that starts with a dash

### ISSUE THREAD

**Issue by mbleigh** [travis-ci/travis.rb#336]
If I do

    travis encrypt --add deploy.token '-something-that-starts-with-a-dash'

I get an `invalid option` error. This happens regardless of whether I quote the value or not. I can understand this error in a non-quotes value, but Travis should be able to handle the quotes argument appropriately.

**Comment by envygeeks** [comment]
@mbleigh that's how most CLI's work, quoting it does not escape the "-", it tells the CLI that it's all a single argument, try: `travis encrypt --add deploy.token -- -something-that-starts-with-a-dash`

**Comment by BanzaiMan** [comment]
@envygeeks's workaround works.

I am closing this now, but if anyone feels strongly about documenting this, we will welcome PR.
