### ISSUE TITLE
travis setup heroku fail with remote distinct from origin

### ISSUE THREAD

**Issue by matiasmasca** [travis-ci/travis.rb#339]
Hi,
I have problems when I tried to run "travis setup heroku" over a repository who has a remote branch called "cuba" instead of "origin". The CLI showed me a message about he could not find the repository.

**Comment by BanzaiMan** [comment]
I ran a quick check with a non-`master` Heroku app, and it seems to work. If you still see this problem, please report with the shell session history, as well as the report output. Thanks.
