### ISSUE TITLE
--debug does not show API requests

### ISSUE THREAD

**Issue by probonopd** [travis-ci/travis.rb#347]
`--debug` is supposed API requests. I would have hoped it would show the actual GET/POST requests, but it does not:

```
me@host:~$ travis token --debug
** Loading "/home/me/.travis/config.yml"
** Timeout::Error: execution expired
Your access token is xxxxxxxxxxxxxxxxx
** Storing "/home/me/.travis/config.yml"
```

Here is my system:

```
me@host:~$ travis report 
System
Ruby:                     Ruby 1.9.3-p484
Operating System:         Ubuntu 14.04
RubyGems:                 RubyGems 1.8.23

CLI
Version:                  1.8.0
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2015-12-17 04:52:47 +0100

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (current)
```

How can I see the GET/POST requests (including their URL and body)?

**Comment by BanzaiMan** [comment]
Not sure how you got a `Timeout::Error`, but `token` command does not make any HTTP requests; it simply reads the data in the config file and reports it. If the token is not available, it will advise you to run `travis login` (for which `--debug` should be effective for printing HTTP requests).
