### ISSUE TITLE
encrypting travis in CLI with non-default GitHub URL

### ISSUE THREAD

**Issue by kevinSuttle** [travis-ci/travis.rb#348]
Apparently it doesn't like GitHub Enterprise SSH domains. 

```bash
❯ travis encrypt "MY_SLACK_INSTANCE:TOKEN" --add notifications.slack
Invalid scheme format: git@MYDOMAIN.BIZ
for a full error report, run travis report
```
So I ran `sudo gem update`, even though I _just_ installed Travis not 20 minutes ago. 

```bash
❯ travis encrypt "MY_SLACK_INSTANCE:TOKEN" --add notifications.slack
private method `load' called for Psych:Module
for a full error report, run travis report
```

And getting this on login
```
/Users/kevinSuttle/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/travis-1.8.0/lib/travis/cli/api_command.rb:162:in `endpoint_option': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/kevinSuttle/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/travis-1.8.0/lib/travis/cli/command.rb:213:in `rescue in execute'
	from /Users/kevinSuttle/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/travis-1.8.0/lib/travis/cli/command.rb:191:in `execute'
	from /Users/kevinSuttle/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/travis-1.8.0/lib/travis/cli.rb:64:in `run'
	from /Users/kevinSuttle/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/travis-1.8.0/bin/travis:18:in `<top (required)>'
	from /Users/kevinSuttle/.rbenv/versions/2.2.3/bin/travis:23:in `load'
	from /Users/kevinSuttle/.rbenv/versions/2.2.3/bin/travis:23:in `<main>'
```

**Comment by ssm** [comment]
The "travis encrypt" command fails with "Invalid scheme format" if the SSH remote URL is on the format "git@github.com:user/repo.git" (scp style), while it succeeds if the remote is "ssh://git@github.com/user/repo.git" (URI style).

If the .git/config file contains:

    [travis]
        slug = <user>/<repo>

using the scp style remote address does not fail.


I suspect it tries to parse everything before ":" as the URI scheme, but the remote address for a ssh url often defaults to using the "scp" style (user@host:repo).

**Comment by kevinSuttle** [comment]
Thanks. Do you have suggestions on how to address this?
I'm using rbenv, and have been getting the same error since running `sudo gem update`. _Any_ command I run with travis now results in the same error.

```ruby
private method `load' called for Psych:Module
for a full error report, run travis report
```

**Comment by ssm** [comment]
Until this is fixed in the code, you probably need  to either add the [travis] block to your $repo/.git/config with the correct value, or change the git remote URI for the repository to a ssh:// git url.

**Comment by kevinSuttle** [comment]
Got it to work. I needed to `travis login -X #(not I)`. Thanks for your help @ssm!
