### ISSUE TITLE
Problem with installation on OS X

### ISSUE THREAD

**Issue by arunvelsriram** [travis-ci/travis.rb#350]
I installed travis client using `gem install travis -v 1.8.0 --no-rdoc --no-ri`. 
The installation seems to be successful but when I tried executing `travis version` following error occurs  
```
/Users/arunvelsriram/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2157:in `method_missing': undefined method `this' for #<Gem::Specification:0x3ff92d485114 travis-1.8.0> (NoMethodError)
	from /Users/arunvelsriram/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1056:in `find_active_stub_by_path'
	from /Users/arunvelsriram/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:63:in `require'
	from /Users/arunvelsriram/.rvm/gems/ruby-2.1.2/gems/travis-1.8.0/bin/travis:7:in `<top (required)>'
	from /Users/arunvelsriram/.rvm/gems/ruby-2.1.2/bin/travis:23:in `load'
	from /Users/arunvelsriram/.rvm/gems/ruby-2.1.2/bin/travis:23:in `<main>'
	from /Users/arunvelsriram/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/arunvelsriram/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

Am using Ruby 2.1.2p95 installed using RVM.

**Comment by arunvelsriram** [comment]
Problem solved after upgrading to Ruby 2.2.1 and downgrading `addressable` to 2.3.8  
`rvm install 2.2.1`
`gem update --system`
`gem install travis`
`gem uninstall addressable`
`gem install -v2.3.8 addressable`

**Comment by cphrmky** [comment]
Just found this issue after running into the same issue having installed latest version of the `travis` gem on the latest version of OSX.  This fix above worked, but why is this happening?

**Comment by emilesilvis** [comment]
Also seeing this.
