### ISSUE TITLE
travis setup releases problem

### ISSUE THREAD

**Issue by mateusmcg** [travis-ci/travis.rb#356]
I'm not really understanding why this is happening so sorry if it is something i'm doing wrong.

I follow these instructions to install travis:
https://github.com/travis-ci/travis.rb#installation

I've tried this with a lot of ruby versions (1.9.3 / 2.0.0 / 2.2.2...) but when i run the following command:
    $ travis setup releases

It finds my repo and asks for user and pass. But when i type my pass and press enter nothing happens. The console doesn't show anything (I've waited like 30 minutes for a response and nothing).
The next step that should appear would be to set the 'files' that i want to upload i suppose.

I'm using Windows 10 x64 and i've tried with and without Github's Two-Factor Authentication.

I really don't know how to setup my .travis.yml file for the releases deploy without this (Keeping it secure).

**Comment by DanVanAtta** [comment]
There is a "--debug" flag you can pass to setup releases, that output could help (ie: `travis setup releases --debug`

**Comment by BanzaiMan** [comment]
If you are still seeing this problem, please run the command with `--debug` and report the result.

Hopefully, we've fixed the issue while we weren't really trying.

I'm closing this for now.
