### ISSUE TITLE
Trying to use travis.rb to restart a travis job on a different repository

### ISSUE THREAD

**Issue by ericdill** [travis-ci/travis.rb#357]
So I'm trying to install travis.rb on one repository on travis-ci so that I can use it to restart the builds on a different repository. I am currently stuck because after I 

`gem install travis`

I am trying to run 

`travis login --github-token $GH_TOKEN`

but am getting an interactive prompt that is asking if I want to install shell completion: 

`Shell completion not installed. Would you like to install it now? |y|`.  

Is there a way to skip this prompt and either install it or don't?  I don't particularly care if shell completion gets installed since it is not useful if I am only triggering travis.rb programmatically, but I do need to get past this prompt!

[Full .travis.yml] (https://github.com/scikit-beam/scikit-beam-examples/blob/rebuild-docs-on-merge/.travis.yml)

Also, if this seems crazy, it is only because I do not know of a better way to do this.  Is there a more sensible way to do this?

**Comment by BanzaiMan** [comment]
Is there a reason that you are not using Requests API to trigger a build? https://docs.travis-ci.com/user/triggering-builds

**Comment by BanzaiMan** [comment]
The above approach would trigger a different (new) build.

**Comment by ericdill** [comment]
> Is there a reason that you are not using Requests API to trigger a build? https://docs.travis-ci.com/user/triggering-builds

Only because I did not know that you could do it that way. Thanks for bringing it to my attention.

Regarding my initial problem, turns out I can shortcut that Shell completion prompt by just echoing "y" and piping it to the travis login command.  Probably should have realized that sooner.

`echo "y" | travis login --github-token $GH_TOKEN`

Thanks for pointing out the requests API and sorry for the noise!

**Comment by devniel** [comment]
Hi,

I also skipped that initial message, my question is how to install shell completion now ?, I tried with `echo "y" | travis` but got nothing.

Thanks.
