### ISSUE TITLE
travis sync --force does not force a sync when a sync is already in progress

### ISSUE THREAD

**Issue by diffalot** [travis-ci/travis.rb#358]
I'm having trouble getting my account to complete a the first sync after signup on travis-ci.org.

I've tried to `travis sync --force` but the command returns:

```
synchronizing: 409: "{\"message\":\"Sync already in progress. Try again later.\"}"
```

more info:

`travis sync --check` returns:

```
diffalot is currently syncing
```

`travis sync` returns:

```
user is already syncing
```

**Comment by BanzaiMan** [comment]
Sorry about the long neglect. If this is still happening, please reopen it.
