### ISSUE TITLE
What are the minimum Github permissions, when creating a new personal access token?

### ISSUE THREAD

**Issue by necramirez** [travis-ci/travis.rb#366]
On GHE v2.4, the default permissions are:
![image](https://cloud.githubusercontent.com/assets/167253/13074772/b76fe726-d4e1-11e5-803c-6be5f53f7847.png)

Can it be reduced? Not that I need it. Just curious, as I can't find any documentation about it.

**Comment by arvenil** [comment]
![edit_personal_access_token](https://user-images.githubusercontent.com/450355/31292378-784487a4-aad3-11e7-9efe-181876c78407.png)

With just this it worked for me.
