### ISSUE TITLE
Filtering not working when using -p option 

### ISSUE THREAD

**Issue by anarosas** [travis-ci/travis.rb#382]
While using my [test repository](I tried using my test repository =>  https://github.com/anarosas/test-gce), I used the `travis history -p 1` command, and it isn't returning any information, it seems that the filtering is not working properly. 

I tried debugging it using the `--debug --explode` options but got a timeout 

```
$ travis history -p 1  --debug --explode
** Loading "/Users/ana/.travis/config.yml"
** Timeout::Error: execution expired
** GET "repos/anarosas/test-gce"
**   took 0.14 seconds
** GET "builds/" {:repository_id=>7947765}
**   took 0.17 seconds
** Storing "/Users/ana/.travis/config.yml"
```

**Comment by mohammedzee1000** [comment]
When can we expect this to be fixed?

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis.rb/commit/270969cca19ea44d576c9c97be79bd96d21a2aac fixes this.

https://rubygems.org/gems/travis/versions/1.9.1.travis.1219.9
