### ISSUE TITLE
Why is Travis CLI making a folder at H:\.travis

### ISSUE THREAD

**Issue by theTechnoKid** [travis-ci/travis.rb#395]
On Windows 8, Travis tries to make a folder at `H:\.travis` when my default location is `C:\`. I can
t use the CLI at all because of this. Is there a way I can fix this?

**Comment by simi** [comment]
I think you can set `TRAVIS_CONFIG_PATH` env variable to specify custom path.

**Comment by theTechnoKid** [comment]
@simi This worked, thank you!
