### ISSUE TITLE
Repository name is case-sensitive

### ISSUE THREAD

**Issue by rschamp** [travis-ci/travis.rb#401]
When using repositories under our capitalized organization name, I receive e.g., `repository not known to https://api.travis-ci.org/: llk/scratch-www`.  To fix this I provide `--repo=LLK/scratch-www`, but this seems like an error in the client, since I never provided the lowercase version to the client.

**Comment by BanzaiMan** [comment]
What is the command you used? What is the name of the directory (the full path) you invoked the command in? Are you on a case-insensitive file system?

**Comment by rschamp** [comment]
On OS 10.11.5, I am on a case-sensitive file system:
```shell
$ pwd
/Users/rschamp/Scratch/scratch-www

$ travis encrypt TEST=1
repository not known to https://api.travis-ci.org/: llk/scratch-www

$ travis encrypt TEST=1 --repo=LLK/scratch-www
Please add the following to your .travis.yml file:

  secure: "..."

Pro Tip: You can add it automatically by running with --add.
```

The issue isn't the path, it's the name of the repo on Github (unless travis is storing repo information via paths?)

**Comment by BanzaiMan** [comment]
What is the URL for the remote you defined for this local copy? I think that's the value we are using here.

**Comment by rschamp** [comment]
The urls for those remotes are
```
upstream	git@github.com:LLK/scratch-www.git (fetch)
upstream	git@github.com:LLK/scratch-www.git (push)
```

Looking in my .git/config however I see this issue:
```
[travis]
        slug = llk/scratch-www
```

Which I can fix myself. However I did not add that there.

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-ci/issues/3198
