### ISSUE TITLE
encrypt-file makes it easy to leak the secret key

### ISSUE THREAD

**Issue by 23Skidoo** [travis-ci/travis.rb#423]
If one puts the decryption command into a shell script:

```.shell
#!/bin/sh
set -ex

openssl aes-256-cbc -K $encrypted_edaf6551664d_key \
    -iv $encrypted_edaf6551664d_iv -in id_rsa.enc -out id_rsa -d
```

and then runs it from `.travis.yml`, the value passed via the `-K` parameter will be leaked ([example](https://travis-ci.org/haskell/cabal/jobs/145445939)).

I think that `encrypt-file` should at least print a warning about this and there should also be a warning in the documentation.

**Comment by Blaisorblade** [comment]
FWIW: that's true but it happens because of `-x` printing the command line. But since `-x` is very sensible in Travis scripts, documenting this pitfall wherever appropriate is probably still good.

**Comment by BanzaiMan** [comment]
As pointed out, `set -x` causes the command to be printed. There is nothing we can do at this time to prevent it, since the user is instructing to print everything, including the secrets.
