### ISSUE TITLE
Note on Ruby version - upgrade to >2 required

### ISSUE THREAD

**Issue by Kentoseth** [travis-ci/travis.rb#431]
In your documentation, you mention that the apt-get/aptitude version of Ruby is adequate to install the CLI.

This is no longer the case, as the JSON dependency for Travis requires >2 version of Ruby.

The documentation should be adjusted to specify that the Travis-cli will NOT work with versions <2

**Comment by BanzaiMan** [comment]
We require Ruby 2.3 now.
