### ISSUE TITLE
"travis encrypt FOO pass --add" leaves variables unencrypted

### ISSUE THREAD

**Issue by szpak** [travis-ci/travis.rb#436]
When `=` is missing in the command line a line `- secure: xxxxxxxxxxxxxxxx` is added to a .travis.yml file (suggesting everything is ok), but values are kept in an unencrypted form and are visible in a "view config" tab for everyone (as `"global_env": "FOO pass"`). It could easily lead to a credentials leak.

There could be at least a warning generated (if there are valid use cases which have syntax like above). A little bit similar to #6.

Travis.rb 1.8.2.

**Comment by BanzaiMan** [comment]
What exact command did you run?

**Comment by szpak** [comment]
The one put in the issue summary:
```
travis encrypt FOO pass --add
```

**Comment by szpak** [comment]
This probably could be closed as fixed.

More details for further reference in this [blog post](https://blog.travis-ci.com/2016-11-23-security-vulnerability-environment-variables/).
