### ISSUE TITLE
decrypting encrypted file

### ISSUE THREAD

**Issue by piq9117** [travis-ci/travis.rb#437]
So I have `.env.enc` how do I decrypt this?

When I do 
```
$ travis encrypt-file .env.enc .env -d
``` 
And I get this, where do I get the key?
```
key must be 64 characters long and a valid hex number
```
How does my teammate get access to the encrypted file?

**Comment by rudyk5** [comment]
Not fill erorrr kali

**Comment by BanzaiMan** [comment]
You cannot decrypt the file outside of Travis CI. (We store the private key that encrypted the file in our database, and it is not accessible from the outside.)

Please ask the person who originally encrypted the file for the decrypted file.

**Comment by lynxlynxlynx** [comment]
Why is it not possible after using `travis login` though? In my case the key and iv env variables are stored in the travis frontend, where they are masked and irretrievable. If I had initially chosen to add them to the yaml file, they'd be available and decrypting would work.

On a similar note `travis env` can't show the encrypted values.

**Comment by rudyk5** [comment]
seperti itu kahhh
