### ISSUE TITLE
question: is ruby 2.0.0 still the recommended version?

### ISSUE THREAD

**Issue by peggyl** [travis-ci/travis.rb#440]
The [README](https://github.com/travis-ci/travis.rb#installation) recommends Ruby v2.0.0. 

According to the official Ruby page https://www.ruby-lang.org/en/downloads/, 2.0.0 is no longer maintained / EOLed, and 2.1.10 will be EOLed soon. The current stable releases are 2.2.5 and 2.3.1.

Based on this, is the recommended version for travis still 2.0.0? Are there known issues with using 2.3.1?

**Comment by lukebakken** [comment]
For what it's worth, I've been using `2.3.1p112` with no issues this week.

**Comment by mkistler** [comment]
Despite statements in the README, Ruby v2.0.0 is no longer sufficient.  My attempt to install travis 1.8.2 on a Mac with Ruby version `ruby 2.0.0p648` fails with:
```
ERROR:  Error installing travis:
	net-http-persistent requires Ruby version ~> 2.1.
```

**Comment by BanzaiMan** [comment]
Sorry for the long delay.

We will be requiring 2.3 in the not-so-distant future (and the documents will be updated accordingly). In general, though, 2.4 is already EOL'd, so I personally recommend 2.5 or later for everyday use.

I'm closing this for now.
