### ISSUE TITLE
gem install travis not working (OS: Windows 10)

### ISSUE THREAD

**Issue by Shyam-Chen** [travis-ci/travis.rb#450]
![default](https://cloud.githubusercontent.com/assets/13535256/19998378/74b2844a-a2a7-11e6-8c3d-235fda821d5d.PNG)

**Comment by BanzaiMan** [comment]
That error message indicates a problem between your Cygwin installation and rubygems.org.

**Comment by MrTrustworthy** [comment]
Exact same error here on windows 10, but without using Cygwin: Windows commandline, with Ruby installation from http://rubyinstaller.org/.

**Comment by BanzaiMan** [comment]
Thanks for the information. I'm closing this now, but if there's anything for us to do, please reach out.
