### ISSUE TITLE
travis CLI 1.8.3 installation installs incorrect version, or does not correctly know it's own version

### ISSUE THREAD

**Issue by rjminsha** [travis-ci/travis.rb#451]
After recent release of 1.8.3 CLI gives the following message 
``` 
Outdated CLI version, run `gem install travis`.
``` 

Installation of 1.8.3 appears to be confused 
```bash 
$ sudo gem install travis -v 1.8.3 
Password:
Successfully installed travis-1.8.3
Parsing documentation for travis-1.8.3
Done installing documentation for travis after 1 seconds
1 gem installed

robbie at Robbies-MacBook-Pro-2 in ~/code/ [!]
$ travis version 
1.8.2

robbie at Robbies-MacBook-Pro-2 in ~/code/ [!]
$ /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.8.3/bin/travis version 
1.8.2
``` 
Message to update the CLI persists. 
Please advise.

**Comment by BanzaiMan** [comment]
Your ruby installation seems confused. What does `which travis` say? And `sudo which travis`?

**Comment by rjminsha** [comment]
```
$ which travis 
/usr/local/bin/travis

$ sudo which travis 
Password:
/usr/local/bin/travis
``` 
Why would the direct call from the 1.8.3 gem result in 1.8.2 version?

Also note that a number of other developers in my group are having the same issue so I doubt it is limited to my particular environment.

**Comment by BanzaiMan** [comment]
Thanks for the info. I see the problem now. We'll fix it soon and release 1.8.4.

**Comment by BanzaiMan** [comment]
1.8.4 has been released. Let us know if you continue to have problems.

I'm closing this now.

**Comment by rjminsha** [comment]
Thanks 
``` 
robbie at Robbies-MacBook-Pro-2 in ~/code/weather/dig on s3-refactor [!?]
$ gem install travis -v 1.8.4 

robbie at Robbies-MacBook-Pro-2 in ~/code/weather/dig on s3-refactor [!?]
$ travis version 
1.8.4
```
