### ISSUE TITLE
please clarify installation instructions for local users

### ISSUE THREAD

**Issue by chrisbra** [travis-ci/travis.rb#457]
so e.g. do not try to install into system but rather user user-local priviliges:
so instead of `gem install travis -v 1.8.4 --no-rdoc --no-ri` use
`gem install travis -v 1.8.4 --no-rdoc --no-ri  --user-install`

Note: I am no ruby programmer, so the error message was confusing:

    ~/code/vim-appimage/scripts (git)-[master]- % gem install travis -v 1.8.4 --no-rdoc --no-ri
    Fetching: multipart-post-2.0.0.gem (100%)
    ERROR:  While executing gem ... (Gem::FilePermissionError)
        You don't have write permissions for the /var/lib/gems/2.3.0 directory.

**Comment by rws-github** [comment]
I had the same problem and the corrected command works.

**Comment by up9cloud** [comment]
i can install with `--user-install`.

but

```console
$ travis
-bash: travis: command not found
```

i solved this by https://github.com/travis-ci/travis-ci/issues/2055#issuecomment-326725847
```sh
brew install ruby
gem update --system
gem install travis -v 1.8.8 --no-rdoc --no-ri
```

**Comment by mcraveiro** [comment]
I think the problem reported by @up9cloud was due to not placing the local gem directory on the path. I managed to run travis after that. I submitted a PR to address this issue, if you think it does please close this ticket. Thanks.
