### ISSUE TITLE
Lint fails when Travis is configured to use Yarn package manager for nodejs projects

### ISSUE THREAD

**Issue by ali** [travis-ci/travis.rb#469]
I have a `.travis.yml` for a nodejs project [configured to use the Yarn package manager][nodejs-docs-yarn]. When I try to lint my config with the `travis lint` command I get this warning:

```
Warnings for .travis.yml:
[x] in cache section: unexpected key yarn, dropping
```

The part of my `.travis.yml` it's complaining about is:

```yml
cache:
  yarn: true
```

That part should be okay according to my own experience using this config and also [the docs][nodejs-docs-yarn]:

![2017-01-04 at 12 12 pm](https://cloud.githubusercontent.com/assets/515861/21651582/2acd567a-d277-11e6-8862-865cc0085d1d.png)

This bug doesn't really impact me much, as I'm still able to lint my config and use this config to build my project on Travis.

[nodejs-docs-yarn]: https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Travis-CI-supports-yarn
[yarn-announcement]: https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn

**Comment by victorboissiere** [comment]
Same issue here

**Comment by ndresx** [comment]
With just `cache: yarn`, the lint output looks similar:
```
[x] value for cache section is empty, dropping
[x] in cache section: unexpected key yarn, dropping
```

**Comment by jameswlane** [comment]
I am also getting this issue with `cache: yarn`

**Comment by BanzaiMan** [comment]
The `lint` command has gone through substantial changes recently. If you still see this problem, please open a new issue.
