### ISSUE TITLE
Repeatedly asks for Two-factor authentication code during login

### ISSUE THREAD

**Issue by beccanelson** [travis-ci/travis.rb#474]
I was unable to log in, because it is repeatedly asking for the Two-factor authentication code. Entering the same code doesn't work, and the app doesn't show that I'm logged in after quitting the process.

This is what the login flow looked like: 

```
Username: <username>
Password for <username>: **********
Two-factor authentication code for <username>: 123456
Successfully logged in as <username>!
Two-factor authentication code for <username>:
Two-factor authentication code for <username>:
Two-factor authentication code for <username>:
...
```

**Comment by ungoldman** [comment]
Can confirm this was happening for me too with latest version of cli. Ended up generating github token as a workaround.

**Comment by Shana6** [comment]
Still not working for me either, if someone could look at this, it'd be awesome, seeing as it's a problem dating all the way back to mid January.

**Comment by BanzaiMan** [comment]
If you are still getting this error, could you send email to support@travis-ci.com?

**Comment by Shana6** [comment]
personally I am not getting this problem as I've found a workaround (tokens) so if anyone else has this problem they should post it as ~~I'm too lazy to try to send an issue email seeing as it doesn't affect me and someone else can do it~~ it's important that this gets reported via email too.

**Comment by gnzlbg** [comment]
I am having this issue as well.

**Comment by HankQuiter** [comment]
same problem

**Comment by teresa-recursion** [comment]
same problem

**Comment by BanzaiMan** [comment]
If you still encounter this problem, please include `--debug` output (and redact GitHub authentication form it).

I'm closing this as stale for the time being.
