### ISSUE TITLE
Log-related commands and methods broken

### ISSUE THREAD

**Issue by leusonmario** [travis-ci/travis.rb#488]
I just tryed to execute the code [below](https://github.com/travis-ci/travis.rb#artifacts)

> require 'travis'
> 
> repo = Travis::Repository.find('travis-ci/travis.rb')
> job  = repo.last_build.jobs.first
> puts job.log.body

But the script does not work and allways returns the same answer:

> undefined method `body' for nil:NilClass (NoMethodError)

Travis version: 1.8.8

**Comment by leusonmario** [comment]
travis report --pro

System
Ruby:                     Ruby 2.3.1-p112
Operating System:         LinuxMint 17.3
RubyGems:                 RubyGems 2.6.11

CLI
Version:                  1.8.8
Plugins:                  none
Auto-Completion:          no
Last Version Check:       2017-03-20 19:33:22 -0300

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                as "leusonmario"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, insecure)
pro:                      https://api.travis-ci.com/ (access token, current)

Last Exception
An error occurred running `travis logs --org`:
    NoMethodError: undefined method `body' for nil:NilClass
        from /home/leuson/.rvm/gems/ruby-2.3.0/gems/travis-1.8.9.travis.826.4/lib/travis/cli/logs.rb:39:in `display_log'
        from /home/leuson/.rvm/gems/ruby-2.3.0/gems/travis-1.8.9.travis.826.4/lib/travis/cli/logs.rb:23:in `run'
        from /home/leuson/.rvm/gems/ruby-2.3.0/gems/travis-1.8.9.travis.826.4/lib/travis/cli/command.rb:198:in `execute'
        from /home/leuson/.rvm/gems/ruby-2.3.0/gems/travis-1.8.9.travis.826.4/lib/travis/cli.rb:64:in `run'
        from /home/leuson/.rvm/gems/ruby-2.3.0/gems/travis-1.8.9.travis.826.4/bin/travis:18:in `<top (required)>'
        from /home/leuson/.rbenv/versions/2.3.1/bin/travis:23:in `load'
        from /home/leuson/.rbenv/versions/2.3.1/bin/travis:23:in `<main>'

**Comment by eupharis** [comment]
I have the same problem. `show` and `history` work fine. just not `logs`
```
System
Ruby:                     Ruby 2.3.1-p112
Operating System:         Ubuntu 16.04
RubyGems:                 RubyGems 2.6.11

CLI
Version:                  1.8.8
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2017-03-21 09:44:43 -0700

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                as "eupharis"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token)
pro:                      https://api.travis-ci.com/ (access token, current)

Last Exception
An error occurred running `travis logs --pro`:
    NoMethodError: undefined method `body' for nil:NilClass
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/logs.rb:39:in `display_log'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/logs.rb:23:in `run'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/command.rb:198:in `execute'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli.rb:64:in `run'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:22:in `load'
        from /usr/local/bin/travis:22:in `<main>'
```

**Comment by liorrozen** [comment]
Hi, I am also having issues running the `logs` command. This was for a private repository.

```
$ travis report --pro
System
Ruby:                     Ruby 2.3.1-p112
Operating System:         Mac OS X 10.12.3
RubyGems:                 RubyGems 2.5.1

CLI
Version:                  1.8.8
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2017-03-21 18:52:49 +0200

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                as "liorrozen"
Verify SSL:               yes
Enterprise:               no

Endpoints
pro:                      https://api.travis-ci.com/ (access token, current)
org:                      https://api.travis-ci.org/ (access token)

Last Exception
An error occurred running `travis logs --pro`:
    NoMethodError: undefined method `body' for nil:NilClass
        from /Users/liorr/.rvm/gems/ruby-2.3.1/gems/travis-1.8.8/lib/travis/cli/logs.rb:39:in `display_log'
        from /Users/liorr/.rvm/gems/ruby-2.3.1/gems/travis-1.8.8/lib/travis/cli/logs.rb:23:in `run'
        from /Users/liorr/.rvm/gems/ruby-2.3.1/gems/travis-1.8.8/lib/travis/cli/command.rb:198:in `execute'
        from /Users/liorr/.rvm/gems/ruby-2.3.1/gems/travis-1.8.8/lib/travis/cli.rb:64:in `run'
        from /Users/liorr/.rvm/gems/ruby-2.3.1/gems/travis-1.8.8/bin/travis:18:in `<top (required)>'
        from /Users/liorr/.rvm/gems/ruby-2.3.1/bin/travis:23:in `load'
        from /Users/liorr/.rvm/gems/ruby-2.3.1/bin/travis:23:in `<main>'
        from /Users/liorr/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
        from /Users/liorr/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by BenKanouse** [comment]
Same issue here. It seems that all instances of Travis::Client::Job are returning nil for the `log` and `log_id` method. So naturally any method I chain off of that method returns an undefined method for nil error.

**Comment by meatballhat** [comment]
I'm pretty sure a recent change I shipped to the API is at fault: https://github.com/travis-ci/travis-api/pull/427

I'm currently working on https://github.com/travis-ci/travis-api/pull/453, which solves *some* issues, but doesn't yet play nicely with this library.

**Comment by meatballhat** [comment]
This PR has been merged and deployed for both public and private repos: https://github.com/travis-ci/travis-api/pull/453

Please holler if you're still seeing issues! :heart:

**Comment by leusonmario** [comment]
Thank you :) !!

**Comment by matthewmorley** [comment]
I'm seeing this behavior, started sometime yesterday for me (against a private repo). I thought I commented earlier today... but not seeing it now, so reposting.

**Comment by eupharis** [comment]
This broke again for me in the same way as well. Same `travis report --pro` I posted earlier in this ticket.

**Comment by leusonmario** [comment]
@meatballhat could you please check again this issue?
I have again the same problem posted some days ago.

**Comment by BenKanouse** [comment]
@meatballhat It seems like this issue was closed without fixing it.

Should it be re-opened?

**Comment by VictorDenisov** [comment]
#494 describes the same issue I presume.
