### ISSUE TITLE
Failed to display log from command line

### ISSUE THREAD

**Issue by VictorDenisov** [travis-ci/travis.rb#494]
System
Ruby:                     Ruby 2.1.5-p273
Operating System:         Debian 8.7
RubyGems:                 RubyGems 2.2.2

CLI
Version:                  1.8.8
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2017-03-29 17:21:05 -0700

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                as "VictorDenisov"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ ()
pro:                      https://api.travis-ci.com/ (access token, current)

Last Exception
An error occurred running `travis logs --pro`:
    NoMethodError: undefined method `body' for nil:NilClass
        from /var/lib/gems/2.1.0/gems/travis-1.8.8/lib/travis/cli/logs.rb:39:in `display_log'
        from /var/lib/gems/2.1.0/gems/travis-1.8.8/lib/travis/cli/logs.rb:23:in `run'
        from /var/lib/gems/2.1.0/gems/travis-1.8.8/lib/travis/cli/command.rb:198:in `execute'
        from /var/lib/gems/2.1.0/gems/travis-1.8.8/lib/travis/cli.rb:64:in `run'
        from /var/lib/gems/2.1.0/gems/travis-1.8.8/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:23:in `load'
        from /usr/local/bin/travis:23:in `<main>'

**Comment by SUPERCILEX** [comment]
Same error:
```
System
Ruby:                     Ruby 2.3.1-p112
Operating System:         Ubuntu 16.04
RubyGems:                 RubyGems 2.5.1

CLI
Version:                  1.8.8
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2017-03-30 11:47:53 -0700

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                as "SUPERCILEX"
Verify SSL:               yes
Enterprise:               no

Endpoints
pro:                      https://api.travis-ci.com/ (access token, current)
org:                      https://api.travis-ci.org/ (access token)

Last Exception
An error occurred running `travis logs --pro`:
    NoMethodError: undefined method `body' for nil:NilClass
        from /var/lib/gems/2.3.0/gems/travis-1.8.9.travis.826.4/lib/travis/cli/logs.rb:39:in `display_log'
        from /var/lib/gems/2.3.0/gems/travis-1.8.9.travis.826.4/lib/travis/cli/logs.rb:23:in `run'
        from /var/lib/gems/2.3.0/gems/travis-1.8.9.travis.826.4/lib/travis/cli/command.rb:198:in `execute'
        from /var/lib/gems/2.3.0/gems/travis-1.8.9.travis.826.4/lib/travis/cli.rb:64:in `run'
        from /var/lib/gems/2.3.0/gems/travis-1.8.9.travis.826.4/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:23:in `load'
        from /usr/local/bin/travis:23:in `<main>'
```

**Comment by MattMcMurray** [comment]
I'm getting this error as well. 

```System
Ruby:                     Ruby 2.3.1-p112
Operating System:         Ubuntu 16.04
RubyGems:                 RubyGems 2.6.10

CLI
Version:                  1.8.8
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2017-03-31 15:57:24 -0500

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                as "MattMcMurray"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token)
pro:                      https://api.travis-ci.com/ (access token, current)

Last Exception
An error occurred running `travis logs --pro`:
    NoMethodError: undefined method `body' for nil:NilClass
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/logs.rb:39:in `display_log'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/logs.rb:23:in `run'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/command.rb:198:in `execute'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli.rb:64:in `run'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:22:in `load'
        from /usr/local/bin/travis:22:in `<main>'
```

**Comment by gimlids** [comment]
same

```
$ travis report --pro
System
Ruby:                     Ruby 2.0.0-p648
Operating System:         Mac OS X 10.12.4
RubyGems:                 RubyGems 2.0.14.1

CLI
Version:                  1.8.8
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2017-04-05 17:41:17 -0400

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                as "gimlids"
Verify SSL:               yes
Enterprise:               no

Endpoints
pro:                      https://api.travis-ci.com/ (access token, current)
org:                      https://api.travis-ci.org/ ()

Last Exception
An error occurred running `travis logs --pro`:
    NoMethodError: undefined method `body' for nil:NilClass
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.8/lib/travis/cli/logs.rb:39:in `display_log'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.8/lib/travis/cli/logs.rb:23:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.8/lib/travis/cli/command.rb:198:in `execute'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.8/lib/travis/cli.rb:64:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.8/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:23:in `load'
        from /usr/local/bin/travis:23:in `<main>'
```

**Comment by yanqd0** [comment]
The similar output after `travis report --org`:

> System
> Ruby:                     Ruby 2.1.5-p273
> Operating System:         Debian 8.7
> RubyGems:                 RubyGems 2.2.2
> 
> CLI
> Version:                  1.8.8
> Plugins:                  none
> Auto-Completion:          yes
> Last Version Check:       2017-04-27 14:31:23 +0800
> 
> Session
> API Endpoint:             https://api.travis-ci.org/
> Logged In:                as "yanqd0"
> Verify SSL:               yes
> Enterprise:               no
> 
> Endpoints
> org:                      https://api.travis-ci.org/ (access token, current)
> 
> Last Exception
> An error occurred running `travis logs --org`:
>     NoMethodError: undefined method `body' for nil:NilClass
>         from /var/lib/gems/2.1.0/gems/travis-1.8.8/lib/travis/cli/logs.rb:39:in `display_log'
>         from /var/lib/gems/2.1.0/gems/travis-1.8.8/lib/travis/cli/logs.rb:23:in `run'
>         from /var/lib/gems/2.1.0/gems/travis-1.8.8/lib/travis/cli/command.rb:198:in `execute'
>         from /var/lib/gems/2.1.0/gems/travis-1.8.8/lib/travis/cli.rb:64:in `run'
>         from /var/lib/gems/2.1.0/gems/travis-1.8.8/bin/travis:18:in `<top (required)>'
>         from /usr/local/bin/travis:23:in `load'
>         from /usr/local/bin/travis:23:in `<main>'

**Comment by lbadger** [comment]
Another one.

> System
> Ruby:                     Ruby 2.3.1-p112
> Operating System:         Ubuntu 16.04
> RubyGems:                 RubyGems 2.5.1
> 
> CLI
> Version:                  1.8.8
> Plugins:                  none
> Auto-Completion:          yes
> Last Version Check:       2017-05-05 10:53:30 -0600
> 
> Session
> API Endpoint:             https://api.travis-ci.com/
> Logged In:                as "lbadger"
> Verify SSL:               yes
> Enterprise:               no
> 
> Endpoints
> pro:                      https://api.travis-ci.com/ (access token, current)
> org:                      https://api.travis-ci.org/ ()
> 
> Last Exception
> An error occurred running `travis logs --pro`:
>     NoMethodError: undefined method `body' for nil:NilClass
>         from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/logs.rb:39:in `display_log'
>         from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/logs.rb:23:in `run'
>         from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/command.rb:198:in `execute'
>         from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli.rb:64:in `run'
>         from /var/lib/gems/2.3.0/gems/travis-1.8.8/bin/travis:18:in `<top (required)>'
>         from /usr/local/bin/travis:23:in `load'
>         from /usr/local/bin/travis:23:in `<main>'
> 
>

**Comment by harvinderkaur** [comment]
Is anyone looking at it?

**Comment by marpet** [comment]
I've problems working with logs too. Only the error is different. I haven't found any information about this.

This is the report:
```
C:\Users\Marco\Projects\senbox\s3tbx>travis logs
displaying logs for senbox-org/s3tbx#597.1
SSL_connect returned=1 errno=0 state=error: certificate verify failed
for a full error report, run travis report --org

C:\Users\Marco\Projects\senbox\s3tbx>travis report --org
System
Ruby:                     Ruby 2.3.3-p222
Operating System:         Windows
RubyGems:                 RubyGems 2.5.2

CLI
Version:                  1.8.8
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       never

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "marpet"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)

Last Exception
An error occurred running `travis logs --org`:
    Faraday::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:933:in `connect'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:852:in `start'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:1398:in `request'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:1156:in `get'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/faraday-0.12.1/lib/faraday/adapter/net_http.rb:78:in `perform_request'
```

**Comment by liorrozen** [comment]
@marpet - notice that your error message is different fro others on this thread. It seems like you are seeing `SSLError` problems while connecting to the service where as others are seeing `NoMethodError` issues.

**Comment by marpet** [comment]
Sure, I've noticed this, But it still fits to the caption of the issue.
Do you think I should raise a new issue?

**Comment by liorrozen** [comment]
@marpet - that's your decision :) However I can say that the issue others (myself included) are facing is a bug that was reportedly fixed but has since returned and is yet to be dealt with completely.
See here for more [similar](https://github.com/travis-ci/travis.rb/issues/488) [issues](https://github.com/travis-ci/travis.rb/issues/493).  Since your issue does seem separate from these cases, personally, I would open a different issue. This is just my opinion though :)

**Comment by marpet** [comment]
You'r right. I've created a separate issue: #505

**Comment by hekard2l** [comment]
Same issue here (Windows 10)
```
λ  travis report --pro
System
Ruby:                     Ruby 2.3.3-p222
Operating System:         Windows
RubyGems:                 RubyGems 2.5.2

CLI
Version:                  1.8.8
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       never

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                as "hekard2l"
Verify SSL:               yes
Enterprise:               no

Endpoints
pro:                      https://api.travis-ci.com/ (access token, current)
org:                      https://api.travis-ci.org/ ()

Last Exception
An error occurred running `travis logs --pro`:
    NoMethodError: undefined method `body' for nil:NilClass
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/logs.rb:39:in `display_log'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/logs.rb:23:in `run'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/command.rb:198:in `execute'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli.rb:64:in `run'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.8/bin/travis:18:in `<top (required)>'
        from C:/Ruby23-x64/bin/travis:22:in `load'
        from C:/Ruby23-x64/bin/travis:22:in `<main>'
```

**Comment by lanej** [comment]
Another

```
» travis report --pro
System
Ruby:                     Ruby 2.3.0-p0
Operating System:         Mac OS X 10.12.5
RubyGems:                 RubyGems 2.5.1

CLI
Version:                  1.8.8
Plugins:                  none
Auto-Completion:          no
Last Version Check:       2017-06-28 09:20:44 -0700

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                as "lanej"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ ()
pro:                      https://api.travis-ci.com/ (access token, current)

Last Exception
An error occurred running `travis logs --pro`:
    NoMethodError: undefined method `body' for nil:NilClass
        from /Users/jlane/.gem/ruby/2.3.0/gems/travis-1.8.8/lib/travis/cli/logs.rb:39:in `display_log'
        from /Users/jlane/.gem/ruby/2.3.0/gems/travis-1.8.8/lib/travis/cli/logs.rb:23:in `run'
        from /Users/jlane/.gem/ruby/2.3.0/gems/travis-1.8.8/lib/travis/cli/command.rb:198:in `execute'
        from /Users/jlane/.gem/ruby/2.3.0/gems/travis-1.8.8/lib/travis/cli.rb:64:in `run'
        from /Users/jlane/.gem/ruby/2.3.0/gems/travis-1.8.8/bin/travis:18:in `<top (required)>'
        from /Users/jlane/.gem/ruby/2.3.0/bin/travis:23:in `load'
        from /Users/jlane/.gem/ruby/2.3.0/bin/travis:23:in `<main>'
```

**Comment by lanej** [comment]
The problem seems to be with the server-side presenter.  Requesting the jobs URL with `Accept: application/json;charset=utf-8` returns log information, `Accept: application/vnd.travis-ci.2+json` does not.

**Comment by lanej** [comment]
Looking at the [api code](https://github.com/travis-ci/travis-api/blob/1e5dcf9/lib/travis/api/app/endpoint/jobs.rb#L19), the `/jobs/:id` endpoint requires a `include_log_id` parameter or the `User-Agent` needs to start with `Travis`.

**Comment by lanej** [comment]
Original offending PR is https://github.com/travis-ci/travis-api/pull/457

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
This issue has been fixed!

PS: Thanks for the investigation @lanej!
