### ISSUE TITLE
travis lint: "unexpected key go_import_path, dropping"

### ISSUE THREAD

**Issue by ankon** [travis-ci/travis.rb#495]
When using `travis lint` on a go project (specifically kubernetes/ingress) this is logged:
~~~~
$ travis lint
Warnings for .travis.yml:
[x] unexpected key go_import_path, dropping
~~~~

This is confusing, and probably caused by the issue also reported as https://github.com/travis-ci/travis-yaml/issues/110

**Comment by BanzaiMan** [comment]
The `lint` command has gone through substantial changes recently. If you still see this problem, please open a new issue.
