### ISSUE TITLE
Add a way to get the public key for the repo

### ISSUE THREAD

**Issue by sarahhodne** [travis-ci/travis.rb#50]
This is useful if you want to re-add the deploy key.

Something like 

```
$ travis deploy-key
ssh-rsa AAAAB3Nza…
```

**Comment by oncletom** [comment]
So if I understand well, if I use `travis pubkey`and appends its output to `~/.ssh/authorized_keys` on a server I deploy to, it is not going to work?

It would be so so useful for script deploy; I use `rsync` to deploy artifacts and that would be massively helpful.
