### ISSUE TITLE
encrypt-file generates wrong path

### ISSUE THREAD

**Issue by ioquatix** [travis-ci/travis.rb#501]
```
% travis encrypt-file config/deploy.key                                     
encrypting config/deploy.key for XXX/www.YYY.co.nz
storing result as deploy.key.enc
storing secure env variables for decryption

Please add the following to your build script (before_install stage in your .travis.yml, for instance):

    openssl aes-256-cbc -K $encrypted_XXX_key -iv $encrypted_XXX_iv -in deploy.key.enc -out config/deploy.key -d

Pro Tip: You can add it automatically by running with --add.

Make sure to add deploy.key.enc to the git repository.
Make sure not to add config/deploy.key to the git repository.
Commit all changes to your .travis.yml.
```

The `-in` path is wrong, it should be `config/deploy.key.enc`.

**Comment by ioquatix** [comment]
I would like to add to this, I actually reported this slightly incorrectly.

The travis-encrypt command dumps the file directly into the root directory, which isn't what I want. I want the file to be in the same path but + ".enc". So, in theory, the above command is sort of correct, but I prefer if the output file is also `config/deploy.key.enc`.

Thanks for your time.

**Comment by ioquatix** [comment]
Additionally, I'd be happy to make a PR to fix this, if that's of use.

**Comment by lucasvanlierop** [comment]
Hi @ioquatix I have a similar issue. When I run travis-cli in a sub dir it writes the input file including the subdir to `.travis.yml` (which is 2 levels higher in the tree) But it forgets to add current working directory to the in/out paths. More specific:

```sh
cd sub/dir
travis encrypt-file ./ssh/deploy ./ssh/deploy.enc --add
```
.travis.yml:

```
before_install:
  - openssl aes-256-cbc -K $encrypted_123_key -iv $encrypted_123_iv
    -in ./.ssh/deploy.enc -out ./.ssh/deploy -d
```
I expected to see:

```
before_install:
  - openssl aes-256-cbc -K $encrypted_123_key -iv $encrypted_123_iv
    -in ./sub/dir/.ssh/deploy.enc -out ./sub/dir/.ssh/deploy -d
```
