### ISSUE TITLE
travis encrypt fails

### ISSUE THREAD

**Issue by acgetchell** [travis-ci/travis.rb#508]
┌─[adam][hapkido][±][coverity-scan ✓][~/causal-sets-explorer]
└─▪ travis encrypt COVERITY_SCAN_TOKEN=XmUJl-bM4qznBXTQ6f-fTw
Did not recognize your adapter specification (dlopen(/usr/local/lib/ruby/gems/2.4.0/gems/json-2.0.3/lib/json/ext/parser.bundle, 9): Library not loaded: /usr/local/opt/ruby/lib/libruby.2.4.0.dylib
  Referenced from: /usr/local/lib/ruby/gems/2.4.0/gems/json-2.0.3/lib/json/ext/parser.bundle
  Reason: image not found - /usr/local/lib/ruby/gems/2.4.0/gems/json-2.0.3/lib/json/ext/parser.bundle).
for a full error report, run travis report

Full error report here:

https://gist.github.com/acgetchell/9121ba2793b3f6f61f3629b2b56b12ec

**Comment by ara-ta3** [comment]
I'm also faced this error.
In my case, I didn't install json library. 
So, I ran the command of `gem install json`, and then this error never occurs.
I hope the problem will be solved by the information.
