### ISSUE TITLE
Cannot install on El Capitan

### ISSUE THREAD

**Issue by Typecell** [travis-ci/travis.rb#516]
`ERROR:  While executing gem ... (Errno::EPERM).
    Operation not permitted - /usr/bin/travis`

El Capitan does not allow access to the /usr/ directory, even with sudo, due to SIP (System Integrity Protection).

**Comment by tnine** [comment]
How did you resolve this issue?  I'm also experiencing this problem.

**Comment by tnine** [comment]
For anyone else experiencing this issue, I resolved by adding the following line to my `~/.gemrc` file

`gem: -n/usr/local/bin`

This installs the `travisci` binary to `/usr/local/bin`

**Comment by grepped** [comment]
Sorry for the late update, I disabled SIP and that resolved my issue
