### ISSUE TITLE
Per travis lint, "elixir" is not supported

### ISSUE THREAD

**Issue by gmile** [travis-ci/travis.rb#525]
It appears that `travis lint` does not support elixir. When run from an elixir project (https://github.com/Nebo15/ehealth.api), I get this:

```
$ travis lint
Warnings for .travis.yml:
[x] in language section: illegal value elixir, defaulting to ruby
[x] unexpected key elixir, dropping
[x] specified otp_release, but setting is not relevant for ruby
$
```

**Comment by bcardarella** [comment]
Bumping this, its been over a year and half without any response from the Travis team. What is the status on this? I am still seeing this issue with version 1.8.9

**Comment by adkron** [comment]
BUMP

**Comment by BanzaiMan** [comment]
The `lint` command has gone through substantial changes recently. If you still see this problem, please open a new issue.
