### ISSUE TITLE
Encrypting Multiple Files Update

### ISSUE THREAD

**Issue by amc6** [travis-ci/travis.rb#549]
The help documentation says that the only way to encrypt multiple files is to tar them together and then encrypt the resulting archive. However the documentation also links to this issue (https://github.com/travis-ci/travis.rb/issues/239#issuecomment-69240526) that seems to offer a workaround that reuses the same key and iv to encrypt multiple files. I'm far from an expert, but I believe this is totally insecure at worst and possibly insecure at best: https://security.stackexchange.com/questions/1093/forced-into-using-a-static-iv-aes. Given that this workaround is not mentioned in the official docs, I suspect someone at travis has already realized this. But it would be nice to update that issue, so that users (like me) don't go searching for another workaround and think that reusing the iv is acceptable. I would have commented myself, but the thread is locked.

As an aside, could encrypting multiple files not be solved by having travis encrypt-file upload the new key and iv pair under a new env variable key name? So for example, running `travis encrypt-file super_secret.txt` would produce env variables `$encrypted_0a6446eb3ae3_key-1` and `$encrypted_0a6446eb3ae3_iv-1` and then running `travis encrypt-file even_more_super_secret.txt` would produce env variables `$encrypted_0a6446eb3ae3_key-2` and `$encrypted_0a6446eb3ae3_iv-2`? I suspect you would want to use a UUID instead of trying to generate sequential ids, but the key would just be to ensure that old keys and ivs are never overwritten.

**Comment by BanzaiMan** [comment]
Thanks for alerting us about the potential security risk about reusing the IV value. I've removed the comment.

If you feel strongly about your "aside" comment, feel free to open a separate issue, so that it may get the attention it deserves.

Closing this.
