### ISSUE TITLE
Travis-CI command line tool shadows existing executables

### ISSUE THREAD

**Issue by mgbckr** [travis-ci/travis.rb#550]
I installed Travis-CI command line client the other day (on Ubuntu) and found that it installed `launchy` (https://github.com/copiousfreetime/launchy) which shadowed the executable of my app launcher which incidentally is also called `launchy` (https://www.launchy.net/). Took my while to figure this out ;) Maybe it would make sense to check if the installed gems will shadows anything before installing them and putting them on the PATH? 

Also see: https://github.com/copiousfreetime/launchy/issues/120

**Comment by BanzaiMan** [comment]
We don't use the `launchy` executable; just the `Launchy` class. If Launchy is installing an executable, there is not much we can do. (You can define `LAUNCHY_DEBUG=true` to see what it is doing internally.)

RubyGems does not provide a means of looking into what the dependencies do, so there is very little we can do here.
