### ISSUE TITLE
Invalid Warnings:: matrix.include section: unexpected key (?:osx_image|dist|sudo), dropping

### ISSUE THREAD

**Issue by tlindsay42** [travis-ci/travis.rb#559]
### Problem statement

I defined my matrix as shown below per the [multi-OS matrix documentation](https://docs.travis-ci.com/user/multi-os/#Example-Multi-OS-Build-Matrix), and received the following warnings when linting.  I decided to disregard them since it was listed in the official documentation and successfully deployed.  This build matrix config has worked for me ever since and no longer tags the Trusty jobs with xcode (screenshots).

### Build matrix config

```text
$ grep -A6 ^matrix .travis.yml 
matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
        - os: osx
          osx_image: xcode9.1
```

### Client lint warnings

```text
$ travis lint .travis.yml 
Warnings for .travis.yml:
[x] in matrix.include section: unexpected key osx_image, dropping
[x] in matrix.include section: unexpected key dist, dropping
[x] in matrix.include section: unexpected key sudo, dropping
```

### Screenshots

1. Before
![image](https://user-images.githubusercontent.com/11078689/33157977-c284e364-cfcb-11e7-9c99-d71fffcc800f.png)
2. After
![image](https://user-images.githubusercontent.com/11078689/33157797-4367ebcc-cfca-11e7-9ace-c1b80ef3707e.png)

### Travis Report

```text
$ travis report --pro
System
Ruby:                     Ruby 2.4.2-p198
Operating System:         Linux
RubyGems:                 RubyGems 2.6.13

CLI
Version:                  1.8.8
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2017-11-22 21:11:03 -0600

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ ()
pro:                      https://api.travis-ci.com/ (current)

For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

**Comment by BanzaiMan** [comment]
The `lint` command has gone through substantial changes recently. If you still see this problem, please open a new issue.
