### ISSUE TITLE
Using lts/* for Node version returns with error

### ISSUE THREAD

**Issue by d4nyll** [travis-ci/travis.rb#561]
nvm supports the use of `lts/*` syntax to denote the latest LTS version. This is also supported by Travis. However, when using the linter, it throws an error.

```
$ travis lint .travis.yml 
Warnings for .d4nyll/.beja/code/7/.travis.yml:
[x] in node_js section: value lts/* is not a valid version
```
---
Using this [dummy repository](https://github.com/d4nyll/test), Travis was able to detect the correct Node version.

```
0.68s$ git clone --depth=50 --branch=master https://github.com/d4nyll/test.git d4nyll/test
Cloning into 'd4nyll/test'...
remote: Counting objects: 6, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 6 (delta 0), reused 6 (delta 0), pack-reused 0
Unpacking objects: 100% (6/6), done.
$ cd d4nyll/test
$ git checkout -qf 696d0556e43e76845518d5035692731e44fcacc4
nvm.install
3.87s$ nvm install lts/*
Downloading and installing node v8.9.1...
Downloading https://nodejs.org/dist/v8.9.1/node-v8.9.1-linux-x64.tar.xz...
Now using node v8.9.1 (npm v5.5.1)
$ node --version
v8.9.1
$ npm --version
5.5.1
$ nvm --version
0.33.6
install.npm
0.56s$ npm install 
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.
up to date in 0.085s
0.67s$ npm ls
test@1.0.0 /home/travis/build/d4nyll/test
└── (empty)
0.35s$ npm test
> test@1.0.0 test /home/travis/build/d4nyll/test
> echo 'Error: no test specified'
Error: no test specified
The command "npm test" exited with 0.
Done. Your build exited with 0.
```

**Comment by sigo** [comment]
Same here. Linter complain about `lts/*` entry, but builds are completely okay.

**Comment by LucaFranceschini** [comment]
Same here, still happening...

**Comment by byCedric** [comment]
This is also happening for me on windows builds. I've enabled Linux, MacOS and Windows but this is only happening on the Windows builds. [See the build here](https://travis-ci.com/byCedric/GitHub-Website/jobs/151662865).

**Comment by BanzaiMan** [comment]
@byCedric That the value `lts/*` does not work on Windows is a separate issue, which should now be fixed https://travis-ci.community/t/windows-instances-hanging-before-install/250/8 (Please direct all future Windows-related inquiries to https://travis-ci.community/c/windows. Thanks!)

**Comment by BanzaiMan** [comment]
The `lint` command has gone through substantial changes recently. If you still see this problem, please open a new issue.
