### ISSUE TITLE
Installation instructions: ruby-devel package is needed on Fedora

### ISSUE THREAD

**Issue by dreua** [travis-ci/travis.rb#568]
For the installation on Fedora to succeed I needed to install the ruby-devel package:
`sudo dnf install ruby-devel`

Should I add this to the installation instructions? Is this need for development packages restricted to Ubuntu and Fedora or is it like this on most distributions? 
In the latter case it might be better to write a general guide or notice that development packages are needed instead of adding a section for each distribution.

**Comment by BanzaiMan** [comment]
Closing in favor of #758. It no longer depends on native extensions, so the installation should be easier. If the issue persists, feel free to open a new one.
