### ISSUE TITLE
How to turn off "Auto Cancellation" button through command line client 

### ISSUE THREAD

**Issue by zhangch1991425** [travis-ci/travis.rb#572]
Sometimes, I may push my code many times in a short time and I want to see all the results of them. It will be very convenient to turn off the "Auto Cancellation" button on travis website if you have too many repositories.
So can I turn off the "Auto Cancellation" button in command line client ?

**Comment by myii** [comment]
Found this issue before I found that the fix has been merged in #533 -- this issue is resolved and can be closed:

```shell
$ travis settings auto_cancel_pull_requests --disable ...
```
