### ISSUE TITLE
Travis connections to github.com:443 unreliable (frequent timeouts)

### ISSUE THREAD

**Issue by jab** [travis-ci/travis.rb#573]
Hi Travis-CI staff,
Lately my builds for https://travis-ci.org/jab/bidict started to randomly error every 10 or so jobs with:
```
fatal: unable to access 'https://github.com/jab/bidict.git/': Failed to connect to github.com port 443: Connection timed out.
```
Since each time I push a commit to the master branch, it kicks off a build with 9 jobs, the build now errors overall more often than not. 😿  So far manually restarting the errored jobs has caused them to complete successfully, but no one likes to babysit flaky builds.

Can the reliability of Travis's connections to github.com:443 be improved?

(My .travis.yml is [here](https://github.com/jab/bidict/blob/master/.travis.yml) for reference.)

Thanks in advance for taking a look! :blush:

**Comment by BanzaiMan** [comment]
Sorry to hear about this issue, but this is not an issue with this library itself. Please keep an eye on https://traviscistatus.com, where we post our operations updates.

We generally work on improving these infrastructure issues internally as well.

I'm closing this, as there is not a lot for us to do here.

**Comment by jab** [comment]
Thanks @BanzaiMan. I think I opened this quite a while ago, before the Travis-CI community forum existed, which I take it is now the place to report this issue? It has continued to occur intermittently, and there’s an ongoing thread in the forum where I posted a fresh example as recently as last month: https://travis-ci.community/t/travis-python-archive-download-is-flaky/2147/12
