### ISSUE TITLE
travis-1.8.8/lib/travis/client/session.rb:224:in `raw': 429: "Retry later\n" (Travis::Client::Error)

### ISSUE THREAD

**Issue by ChenZhangg** [travis-ci/travis.rb#575]
When I tried to download travis logs, It always reports:
/home/fdse/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/travis-1.8.8/lib/travis/client/session.rb:224:in `raw': 429: "Retry later\n" (Travis::Client::Error)
	from /home/fdse/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/travis-1.8.8/lib/travis/client/session.rb:186:in `get_raw'
	from /home/fdse/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/travis-1.8.8/lib/travis/client/session.rb:166:in `get'
	from /home/fdse/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/travis-1.8.8/lib/travis/client/session.rb:319:in `fetch_one'
	from /home/fdse/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/travis-1.8.8/lib/travis/client/session.rb:128:in `reload'
	from /home/fdse/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/travis-1.8.8/lib/travis/client/entity.rb:208:in `load_attribute'
	from /home/fdse/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/travis-1.8.8/lib/travis/client/entity.rb:54:in `block (2 levels) in attributes'
	from parallelDownloadLog.rb:74:in `block (2 levels) in getRepositoryLog'
	from parallelDownloadLog.rb:73:in `each'
	from parallelDownloadLog.rb:73:in `block in getRepositoryLog'
	from parallelDownloadLog.rb:70:in `each'
	from parallelDownloadLog.rb:70:in `getRepositoryLog'
	from parallelDownloadLog.rb:88:in `block in eachRepository'
	from /home/fdse/.rbenv/versions/2.4.0/lib/ruby/2.4.0/csv.rb:1771:in `each'
	from /home/fdse/.rbenv/versions/2.4.0/lib/ruby/2.4.0/csv.rb:1148:in `block in foreach'
	from /home/fdse/.rbenv/versions/2.4.0/lib/ruby/2.4.0/csv.rb:1299:in `open'
	from /home/fdse/.rbenv/versions/2.4.0/lib/ruby/2.4.0/csv.rb:1147:in `foreach'
	from parallelDownloadLog.rb:87:in `eachRepository'
	from parallelDownloadLog.rb:91:in `<main>'
Does anyone know how to solve this problem?

**Comment by BanzaiMan** [comment]
Sorry for the delay. If you are still experiencing this problem, please include what repository you used, and at what time (in UTC).

In the meantime, hopefully we've made good progress in this library and other areas so that you no longer sees this problem. I'm closing this optimistically.
