### ISSUE TITLE
Error while login

### ISSUE THREAD

**Issue by snimavat** [travis-ci/travis.rb#576]
Doing ```travis login``` results in error error ```(500: "Sorry, we experienced an error.\n\nrequest_id:babdd6a3-6a83-4f3e-b1f5-42816600298d\n")```

Is it just me ?

travis cli version 1.8.8

**Comment by snimavat** [comment]
Not sure what went wrong.. seem to work now. Sorry for the noise.

**Comment by BanzaiMan** [comment]
This looks like a server error. Hopefully we've eradicated it.

If this resurfaces, do let us know.
