### ISSUE TITLE
Provide a simpler way to encrypt variables

### ISSUE THREAD

**Issue by janisozaur** [travis-ci/travis.rb#591]
Right now the docs make user do `gem install travis` and it should install `travis` command in user's `$PATH`. This does not work on my system and is a rather large dependency (ruby, ruby gem, gems travis depends on, travis gem).

This would be unnecessary if there was a simple option in repo's settings to encrypt variables. Right now I can only add secure variables that cannot be exported.

Alternatively, you could provide some short (oneliner?) command using gpg to encrypt the same.

**Comment by janisozaur** [comment]
I thought this was https://github.com/travis-ci/travis-ci repository, but it's not.

Re-filed as https://github.com/travis-ci/travis-ci/issues/9510

**Comment by janisozaur** [comment]
@SuperSandro2000 what do you mean? The point of this issue is to _have_ a web interface.

**Comment by janisozaur** [comment]
Can you point me to where do I export them to `.travis.yml`?

**Comment by SuperSandro2000** [comment]
``
        api_key: $RUBYGEMS_API_KEY
``

**Comment by janisozaur** [comment]
I don't think you understand what the issue is about.

> Right now I can only add secure variables that cannot be exported.

I do know I can have variables _injected_ into my build environment, but this is not what I want. I want to be able to export the encrypted variables out to `.travis.yml`

**Comment by janisozaur** [comment]
The way you mentioned is entirely dependent on the volatile "runtime" configuration and cannot be effectively stored in the build system for proper tracking.

**Comment by SuperSandro2000** [comment]
Now i get it completely.
