### ISSUE TITLE
Homebrew formula fails to build on macOS Mojave

### ISSUE THREAD

**Issue by pshirshov** [travis-ci/travis.rb#605]
```
brew install travis
```

fails with
 
```
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
```

Though development tools are present.

[06.gem.txt](https://github.com/travis-ci/travis.rb/files/2098345/06.gem.txt)

**Comment by yudaprama** [comment]
@pshirshov how you fix this?

**Comment by pshirshov** [comment]
Actually the error message was misleading, there was an issue with a native library travis depends on.

Works for me now.
