### ISSUE TITLE
CLI env command fails for non-admin users

### ISSUE THREAD

**Issue by samongoose** [travis-ci/travis.rb#609]
CLI Tool:
```
> travis env list --debug -r travis-ci/travis-core
** Loading "/Users/samongoose/.travis/config.yml"
** Loading gh
** GET "config"
**   took 0.16 seconds
** GitHub API: HEAD /repos/travis-ci/travis-core
**   took 0.62 seconds
** GET "repos/travis-ci/travis-core"
**   took 0.12 seconds
** GET "users/"
**   took 0.12 seconds
** GET "users/permissions"
**   took 0.14 seconds
not allowed to access environment variables for travis-ci/travis-core
```
vs API:
```
> curl -H "Travis-API-Version: 3" \
  -H "Authorization: token *****" \
  https://api.travis-ci.org/repo/travis-ci%2Ftravis-core/env_vars
{
  "@type": "env_vars",
  "@href": "/repo/travis-ci%2Ftravis-core/env_vars",
  "@representation": "standard",
  "env_vars": [
....
```
The CLI tool blocks[1] non-admin users from interacting with the `env` command. However, the API permissions[2] specify that a user only needs read/write access to the repo to access this command. I suspect if the client-side allowed the command to go through without the permission check, subsequent commands would succeed, as they do with direct API calls.

1: https://github.com/travis-ci/travis.rb/blob/master/lib/travis/cli/env.rb#L18
2: https://developer.travis-ci.com/permissions

**Comment by dgolant** [comment]
https://github.com/travis-ci/travis.rb/pull/652 I have a PR for this here but this tool seems to be unmaintained

**Comment by mteodori** [comment]
I have the same issue, but it happens only on some repositories I have created, not all of them
