### ISSUE TITLE
`travis enable` still uses the old Github API

### ISSUE THREAD

**Issue by BastienM** [travis-ci/travis.rb#625]
Hi everyone,

We recently migrated all of our repositories to the new Github Apps API via the migration gem recently made available, but our current CI still uses `travis enable` to activate the newly created one.
Meaning that all freshly repositories are using the old API, and we must manually execute the migration gem each time.

Is updating the behavior the `enable` action to the new Github standard in the roadmap (considering that the Services API will be deprecated quite soon) ?
And what are my options while waiting for a possible update ? Apart from enabling all my repositories (which is quite unsafe in my opinion) of course.

Best regards.

**Comment by balupton** [comment]
Try `travis enable --com`
