### ISSUE TITLE
Can "Restart build" to use latest .travis.yaml configurations

### ISSUE THREAD

**Issue by cofyc** [travis-ci/travis.rb#642]
I updated .travis.yml and restarted job but it still use old configuration.
However, it uses latest code (by fetch `+refs/pull/<pr-id>/merge:`).
If it's possible to use latest .travis.yaml, it will be very convenient.

**Comment by BanzaiMan** [comment]
Hello, there. This is not a CLI issue. Please consider opening a topic at https://travis-ci.community/ instead. Thanks.

**Comment by cofyc** [comment]
Thanks! My mistake.
