### ISSUE TITLE
Linter contradicts docs for notifications on_pull_requests key

### ISSUE THREAD

**Issue by DDunc** [travis-ci/travis.rb#668]
From the docs:
https://docs.travis-ci.com/user/notifications/#notifications-of-pr-builds-1
```
notifications:
  slack:
    on_pull_requests: false
```
from running`travis lint` with those values from the cli, version 1.8.10

```
Warnings for .travis.yml:
[x] in notifications.slack section: unexpected key on_pull_requests, dropping
```

If there aren't resources available to keep the linter and docs in sync, would you accept a docs PR that collects all of the known outstanding linter issues and gives them more visibility? I'm a big fan of Travis CI and the documentation is very high quality overall, I appreciate all of the work that's gone into it, but these deltas can be confusing.

**Comment by BanzaiMan** [comment]
The `lint` command has gone through substantial changes recently. If you still see this problem, please open a new issue.
