### ISSUE TITLE
ssh URL "Can't figure out GitHub repo name"

### ISSUE THREAD

**Issue by cjp256** [travis-ci/travis.rb#672]
Using the following URL format, I encountered errors on various commands:
`git clone github.com:<org>/<repo>`

Renamed URL to more typical `ssh://git@github.com/<org>/<repo>`, and all was well.

If it matters, the test repo was `github.com:cjp256/ant-hello-world`

**Comment by BanzaiMan** [comment]
`git-clone` may be going out of the way to accommodate your request, but please understand that `github.com:<org>/<repo>` is not a URL. Treating it as one could lead to other problems such as this.

Thanks.
