### ISSUE TITLE
Zombie builds

### ISSUE THREAD

**Issue by adigherman** [travis-ci/travis.rb#675]
If I create a repo, enable it with Travis and push something to it, the CI job(s) are added to the queue. If I erase the repo before the job(s) from the queue start they will stay in the queue and I cannot figure out a way to properly get rid of them. I did try to sync the account, but nothing happened. It looks like the zombie builds get killed after a couple of minutes, but I wish there was a way for the sync operation to properly clear the queue for the repos that were erased from GitHub.

**Comment by BanzaiMan** [comment]
Thanks for the report, but I am afraid this is not a CLI issue. For general Travis CI service issues like this, please use https://travis-ci.community.

Thanks.
