### ISSUE TITLE
Install and authenticate this cli in Travis CI builds automatically

### ISSUE THREAD

**Issue by ghost** [travis-ci/travis.rb#685]
Inside of a Travis CI build this cli should already be installed and authenticated. Instead I need to add generate a GitHub token myself (saved as `GITHUB_TOKEN`) and then run the following in my `.travis.yml` script:
```
gem install travis -v 1.8.10 --no-rdoc --no-ri
travis login --com --github-token "$GITHUB_TOKEN"
```

**Comment by rgleason** [comment]
This did not work for me on windows10, but after installing the most current Ruby
ruby 2.6.5p114 (2019-10-01 revision 67812) [x64-mingw32]

`$ gem install travis `

did work and keys can be encrypted.

It would be wonderful if encryption was make much simpler to do using a web page, similar to appveyor.

**Comment by BanzaiMan** [comment]
Having a live session in a CI does not seem a good idea.
