### ISSUE TITLE
Encryption key size is too small for select projects

### ISSUE THREAD

**Issue by jaraco** [travis-ci/travis.rb#687]
In #221 and #100, I've reported an issue where it seems that the encryption key size is 4096 bits in some projects and 1024 bits in others. I suspect at one point the key size for projects was bumped from 1024 bits to 4096 bits. The difference is particularly important to Python-based workflows because of the recent introduction of PyPI tokens, which are ~130 bytes, over the 117 bytes allowed by a 1024-bit key.

Is it possible to re-generate a key for a project such that it gets a 4096-bit key, short of deleting and re-creating the project?

**Comment by joachimmetz** [comment]
+1 running into the same issue

**Comment by hugovk** [comment]
Also running into this encrypting PyPI tokens for deploy. 

`travis encrypt` works for projects where `.travis.yml` was created on:

* 2018-09-22
* 2017-10-05
* 2017-05-01

But I get "data too large - consider using travis encrypt-file or travis env set" for projects with these dates:

* 2017-04-04
* 2014-03-16
* 2014-11-01

**Comment by hugovk** [comment]
Reported to the Travis CI Community:

* https://travis-ci.community/t/travis-encrypt-data-too-large-for-pypi-tokens-with-older-repos/5792

**Comment by and-semakin** [comment]
Confirm the issue. I can encrypt a PyPI token in [my fork](https://github.com/and-semakin/Flask-User), but can't do that in [the original old repo](https://github.com/lingthio/Flask-User).

**Comment by blueyed** [comment]
Just for reference/info: transferring a repo to an organization does not necessarily help (likely the org is too old already also).
But using two concatenated env vars worked (https://github.com/Vimjas/vint/blob/db881f8fe7127cd092436371643e48903099f114/.travis.yml#L42-L50).

**Comment by ssbarnea** [comment]
Is anyone on Travis working to address this or we should better all move to the CI/CD systems?

**Comment by jaraco** [comment]
Sounds like a solution to me. Thanks!
