### ISSUE TITLE
XCode Ruby 1.9.3 build fails to start, times out

### ISSUE THREAD

**Issue by mtoothman** [travis-ci/travis.rb#690]
See https://travis-ci.com/travis-ci/travis.rb/builds/130758024 and recent master builds.

https://travis-ci.com/travis-ci/travis.rb/jobs/243048849/config
Job never starts.

**Comment by BanzaiMan** [comment]
Thanks for pointing this out. We've removed it from the build matrix. https://github.com/travis-ci/travis.rb/pull/700
