### ISSUE TITLE
encrypt_file.rb: missing path argument in call to env_name from decrypt_command

### ISSUE THREAD

**Issue by joachimmetz** [travis-ci/travis.rb#701]
https://github.com/travis-ci/travis.rb/blob/master/lib/travis/cli/encrypt_file.rb#L70 is missing the path argument for the calls to env_name https://github.com/travis-ci/travis.rb/blob/master/lib/travis/cli/encrypt_file.rb#L79

**Comment by BanzaiMan** [comment]
Closing this in favor of #711.
