### ISSUE TITLE
install & login error

### ISSUE THREAD

**Issue by MakerGYT** [travis-ci/travis.rb#713]
# System
Ruby:                     Ruby 2.6.3-p62
Operating System:         Ubuntu 18.04
RubyGems:                 RubyGems 3.0.3
# Run
```sh
gem install travis -v 1.8.11 --no-rdoc --no-ri
```
`ERROR:  While executing gem ... (OptionParser::InvalidOption)
    invalid option: --no-rdoc`

**Comment by MakerGYT** [comment]
login error
```sh
travis login --com
no implicit conversion of nil into String
```

**Comment by BanzaiMan** [comment]
The install error comes from `gem`. As the message indicates, your `gem` command does not support those flags. We've updated the instructions recently. https://github.com/travis-ci/travis.rb#installation

For the login error, please provide the output of `travis report --pro` immediate after the failing `travis login --com`. Thanks.
