### ISSUE TITLE
travis env set sets env variable per build or for the repository itself?

### ISSUE THREAD

**Issue by mohammedzee1000** [travis-ci/travis.rb#717]
This is more of a question. 
I know `travis env set` lets you set environment variable for build. But what is not clear it does it apply for all future builds of repo or does it do so for for specific build. 

I would love to be able to set env for specific build and restart it from the cli

**Comment by BanzaiMan** [comment]
This applies to the repository settings. For per-build settings, you can use `.travis.yml` or API to add the desired `env` values.

**Comment by mohammedzee1000** [comment]
Ok, I just want to set an env for specific build number(s). How would I use the API to do that?

**Comment by BanzaiMan** [comment]
You'll have to construct the payload how you see fit. "Setting env var value for a specific build number" probably will not be easy, I am afraid. https://docs.travis-ci.com/user/triggering-builds

`travis raw` may or may not deal with V3 requests, so I'd suggest trying with `curl`.
