### ISSUE TITLE
Access public migrated repository with ruby library

### ISSUE THREAD

**Issue by oliverguenther** [travis-ci/travis.rb#729]
We have a tiny script to search through travis logs for ruby rspec failures in our open-source repository (https://github.com/opf/openproject/blob/dev/script/travis_pr_errors)

It basically looks for the repository and searches for a build with the pull request matching the github's branch name.

Today, we migrated the repository from .org to .com, and now only older builds are returned. This is because `Travis::Repository.find('opf/openproject')` still acts on `.org` by default.

I can use `Travis::Pro::Repository` but that requires authentication, but how can I look for builds on the public repository on .com without `Travis::Pro` and logging in? Do we have to manually use sessions now?

**Comment by BanzaiMan** [comment]
In order to interact with .com endpoint, you need to authenticate.

**Comment by oliverguenther** [comment]
That's unfortunate, but thank you for the response!

**Comment by noon2a** [comment]
[]()
