### ISSUE TITLE
`travis show` command should also show the commit

### ISSUE THREAD

**Issue by nikhilo** [travis-ci/travis.rb#739]
`travis show <build_number>` command currently shows following information
```
$ travis show 16
Job #16.1:  Deployment using Travis CI
State:         passed
Type:          push
Branch:        branchname
Compare URL:   https://github.com/company/repo/compare/ddb10956eeb3...c2eca056b4ea
Duration:      6 min 11 sec
Started:       2020-04-23 21:34:50
Finished:      2020-04-23 21:41:01
Allow Failure: false
Config:        os: linux, jdk: openjdk11
```

We tag our built artifacts (docker containers) with commit hash and Travis CI build number.
And we use git tags to trigger deployments using Travis CI build.
Currently, our deploy system (external to Travis CI) can trigger a Travis CI job for a specific commit hash by checking it out, and tagging it appropriately. Although, I would also like to be able to use Travis CI build numbers to be fed to our deploy system. But I couldn't find any way to find out the commit hash for a given Travis CI build number. 
Is it possible to do that? If not, can this be added ? (since this information is already available on the UI)

**Comment by elimuhub** [comment]
Yes @nikhilo
