### ISSUE TITLE
uninitialized constant Faraday::Error::ClientError

### ISSUE THREAD

**Issue by bitsofinfo** [travis-ci/travis.rb#762]
```
$ brew install travis
==> Downloading https://homebrew.bintray.com/bottles/travis-1.9.1.mojave.bottle.tar.gz
Already downloaded: /Users/bof/Library/Caches/Homebrew/downloads/047aa6f7d9f5e0ee6af9f3f89c64eebb642afa8365cd1b36292e8c0fb634841d--travis-1.9.1.mojave.bottle.tar.gz
==> Pouring travis-1.9.1.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/travis/1.9.1: 3,088 files, 17.0MB

$ travis
uninitialized constant Faraday::Error::ClientError
Did you mean?  Faraday::ClientError
for a full error report, run travis report

$ travis report
uninitialized constant Faraday::Error::ClientError
Did you mean?  Faraday::ClientError
for a full error report, run travis report
```

**Comment by bitsofinfo** [comment]
For anyone else wasting hours trying to get travis running on a mac: https://medium.com/@moreless/fix-failed-to-build-gem-native-extension-cannot-find-hearuby-h-16095094094f

**Comment by BanzaiMan** [comment]
I missed this, but for posterity, I'll point out that https://github.com/travis-ci/travis.rb/pull/751 is meant to fix this issue. (It has nothing to do with building native extensions.)

What surprises me, however, is that you are installing 1.9.1, which should require Faraday ~> 1.0 to define the correct constant. My guess is that your `travis` is pointing to a version that is not 1.9.1 (run `travis --version`; `which travis` to confirm).
