### ISSUE TITLE
How to make travis build android app

### ISSUE THREAD

**Issue by AlphaKennyBudy** [travis-ci/travis.rb#772]
I am sorry, I don't know where else to write.  The problem is that I set up `.travis.yml` in [this repo](https://github.com/AlphaKennyBudy/Mentorship-android). And I have a script `postApk.sh`, but it cannot find any built apks in `$TRAVIS_BUILD_DIR/app/build/outputs/apk/release/`, should I add something to my `build.gradle` or to `.travis.yml`? Thank you.

**Comment by BanzaiMan** [comment]
General questions such as this should go to https://travis-ci.community/

Thanks.
