### ISSUE TITLE
An error occurred running `travis setup --org`:

### ISSUE THREAD

**Issue by karthiksonti24** [travis-ci/travis.rb#788]
```sh-session
karthik@karthik-ThinkPad-T480:~/xebialabs/xlr-multi-release-tile$ travis report --org
System
Ruby:                     Ruby 2.7.0-p0
Operating System:         Ubuntu 20.04
RubyGems:                 RubyGems 3.1.2

CLI
Version:                  1.10.0
Plugins:                  none
Auto-Completion:          no
Last Version Check:       2020-12-17 11:19:11 +0530

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "karthiksonti24"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)
com:                      https://api.travis-ci.com/ ()

Last Exception
An error occurred running `travis setup --org`:
    RuntimeError: Not Found
        from /home/karthik/.rvm/gems/ruby-2.4.2/gems/travis-1.10.0/lib/travis/tools/github.rb:212:in `rescue in basic_auth'
        from /home/karthik/.rvm/gems/ruby-2.4.2/gems/travis-1.10.0/lib/travis/tools/github.rb:208:in `basic_auth'
        from /home/karthik/.rvm/gems/ruby-2.4.2/gems/travis-1.10.0/lib/travis/tools/github.rb:216:in `login'
        from /home/karthik/.rvm/gems/ruby-2.4.2/gems/travis-1.10.0/lib/travis/tools/github.rb:81:in `possible_tokens'
        from /home/karthik/.rvm/gems/ruby-2.4.2/gems/travis-1.10.0/lib/travis/tools/github.rb:50:in `each_token'
        from /home/karthik/.rvm/gems/ruby-2.4.2/gems/travis-1.10.0/lib/travis/tools/github.rb:37:in `with_token'
        from /home/karthik/.rvm/gems/ruby-2.4.2/gems/travis-1.10.0/lib/travis/cli/setup/releases.rb:12:in `block in run'
        from /home/karthik/.rvm/gems/ruby-2.4.2/gems/travis-1.10.0/lib/travis/cli/setup/service.rb:61:in `block in deploy'
        from /home/karthik/.rvm/gems/ruby-2.4.2/gems/travis-1.10.0/lib/travis/cli/setup/service.rb:52:in `configure'
        from /home/karthik/.rvm/gems/ruby-2.4.2/gems/travis-1.10.0/lib/travis/cli/setup/service.rb:60:in `deploy'
        from /home/karthik/.rvm/gems/ruby-2.4.2/gems/travis-1.10.0/lib/travis/cli/setup/releases.rb:11:in `run'
        from /home/karthik/.rvm/gems/ruby-2.4.2/gems/travis-1.10.0/lib/travis/cli/setup.rb:55:in `run'
        from /home/karthik/.rvm/gems/ruby-2.4.2/gems/travis-1.10.0/lib/travis/cli/command.rb:200:in `execute'
        from /home/karthik/.rvm/gems/ruby-2.4.2/gems/travis-1.10.0/lib/travis/cli.rb:64:in `run'
        from /home/karthik/.rvm/gems/ruby-2.4.2/gems/travis-1.10.0/bin/travis:18:in `<top (required)>'
        from /home/karthik/.rvm/gems/ruby-2.4.2/bin/travis:23:in `load'
        from /home/karthik/.rvm/gems/ruby-2.4.2/bin/travis:23:in `<main>'


For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```
Can someone help me with this?

**Comment by thefrosty** [comment]
I've got the same issue, but with the `--pro` login flag.

**Comment by elijahchancey** [comment]
I was able to solve this issue by running 
```gem install gh```

If you look at the stack trace, you can follow the exception to 
```
from /var/lib/gems/2.7.0/gems/travis-1.10.0/lib/travis/tools/github.rb:208:in `basic_auth'
```

That's the last successfully executed line before rescue is executed. 

If you look in the source code for github.rb on lines right after line 208, you can see that the gh gem is needed.

Someone should add the gh gem to the installation notes!

**Comment by aarnaud** [comment]
same

**Comment by hellomrbigshot** [comment]
same, but with ```travis login```

**Comment by thefrosty** [comment]
Has anyone tried to make sure the `gh` gem is installed?

**Comment by karthiksonti24** [comment]
@thefrosty Yes, I have that in place

```
skarthik@skarthik-ThinkPad-T480:~/Downloads$ gem info | grep gh
gh (0.18.0)
    Homepage: https://github.com/travis-ci/gh
```

**Comment by BanzaiMan** [comment]
Try logging in to the appropriate API endpoint first (`travis login`). Either:

1. Go to https://github.com/settings/tokens and generate a token with sufficient scopes (See https://docs.travis-ci.com/user/github-oauth-scopes) and pass it with `-g`:
 
        travis login --pro -g d59ef76533a894...........
2. Edit `~/.travis/config.yml` to have something like this at the top level.

        endpoints:
          https://api.travis-ci.org/:
            access_token: XXXXXXXXXXXXXXXXXXXX
          https://api.travis-ci.com/:
            access_token: XXXXXXXXXXXXXXXXXXXX

    The tokens are visible in the [API explorer](https://developer.travis-ci.com/explore/#explorer)'s `curl` header.

**Comment by pmiara** [comment]
> Try logging in to the appropriate API endpoint first (`travis login`). Either:
> 
>     1. Go to https://github.com/settings/tokens and generate a token with sufficient scopes (See https://docs.travis-ci.com/user/github-oauth-scopes) and pass it with `-g`:
>        ```
>         travis login --pro -g d59ef76533a894...........
>        ```
> 
>     2. Edit `~/.travis/config.yml` to have something like this at the top level.
>        ```
>         endpoints:
>           https://api.travis-ci.org/:
>             access_token: XXXXXXXXXXXXXXXXXXXX
>           https://api.travis-ci.com/:
>             access_token: XXXXXXXXXXXXXXXXXXXX
>        ```
>        
>        
>        The tokens are visible in the [API explorer](https://developer.travis-ci.com/explore/#explorer)'s `curl` header. (You need to sign in via GitHub first.)

That solved the issue (at least for me). Thanks!

**Comment by AlFontal** [comment]
I can confirm @BanzaiMan's solution worked for me too.

**Comment by karthiksonti24** [comment]
This one works. Thanks @BanzaiMan

**Comment by SturmB** [comment]
Where is this API Explorer and the curl header, specifically? I must be too dumb to find it.

**Comment by hard-coders** [comment]
@SturmB Move your cursor on `"Authorization: token ~~~~"` then you can see a token.

![image](https://user-images.githubusercontent.com/9651103/108972137-5c5af880-76c6-11eb-9601-9e990fedb43b.png)

**Comment by bateso88** [comment]
When I follow the link provided I just see this:
You can use API Explorer when you are logged in.

I log in and refresh the page and still it just shows the same. Any ideas??

**Comment by Alexand3r** [comment]
> When I follow the link provided I just see this:
> You can use API Explorer when you are logged in.
> 
> I log in and refresh the page and still it just shows the same. Any ideas??

I had the same issue, you either clear the cookies and all site data regarding travis or open an incognito/private window and login again
