### ISSUE TITLE
Error: resource not found ({} ) when running travis command

### ISSUE THREAD

**Issue by deberle** [travis-ci/travis.rb#836]
I am getting this message whenever I try to run a travis command. This is the minimal reproducible example: 
```
$ travis version
1.11.1
$ ruby -v
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]
$ travis status
resource not found ({}
)
```
I am on macOS Ventura / Apple Silicon

**Comment by murtaza-swati** [comment]
Please the answer is #837.
Closing this one as we have duplicate issues.
